### ISSUE TITLE
Source code for custom version of binary meshfix

### ISSUE THREAD

**Issue by vfonov** [simnibs/simnibs#1]
Hello,

can you specify the location of modified source code for meshfix, bundled with SimNIBS? https://github.com/MarcoAttene/MeshFix-V2.1/ seem to be quite different from the binary version included in https://github.com/simnibs/simnibs/tree/master/simnibs/bin/

**Comment by guilhermebs** [comment]
Hi,

Please find it below.

[meshfix.zip](https://github.com/simnibs/simnibs/files/3296213/meshfix.zip)

**Comment by vfonov** [comment]
I put the source into https://github.com/vfonov/MeshFix-V1.5A ,  I hope you don't mind.
