### ISSUE TITLE
Terminal issue or headreco update

### ISSUE THREAD

**Issue by reubebe** [simnibs/simnibs#100]
I run headreco all some days ago on my MacBook 

now all of a sudden I am getting "-bash: headreco: command not found"

I highly suspect it is my MacBook but maybe I could get some help here

**Comment by oulap** [comment]
Hi,
Not sure what happened to your mac, but sounds like the simnibs functions are not in the path anymore (or the shell has changed).
You can try to go into <simnibs_installation_path>/bin and see if headreco is there. If it is, try running from inside the folder. If it runs then you probably just need to add that folder to your path.
