### ISSUE TITLE
Charm availability and documentation 

### ISSUE THREAD

**Issue by tmedani** [simnibs/simnibs#101]
Dear SimNibs team,

Is the Charm process released yet or not? 

I download the latest version of SimNibs from the website, but it seems that Charm is not included.
 
Also, I can't find any documentation to use it. 

Am I looking in the wrong place? could you please show me the right link to the documentation?

Thank you 

![image](https://user-images.githubusercontent.com/37831900/201206154-c8d3921f-3183-4edd-8e6a-836fedc43f56.png)

**Comment by oulap** [comment]
The beta release of simnibs 4 is under "releases" on this github page. Here's the link:

https://github.com/simnibs/simnibs/releases

We will do an official release soon.
