### ISSUE TITLE
doc: UML diagrams 

### ISSUE THREAD

**Issue by ggrrll** [simnibs/simnibs#103]
Hi,

 I have created UML diagrams using `pyreverse` -- I attach them here , if you wanna add them for a better overview of the project 
[classes.pdf](https://github.com/simnibs/simnibs/files/10068447/classes.pdf)
[packages.pdf](https://github.com/simnibs/simnibs/files/10068448/packages.pdf)

**Comment by oulap** [comment]
Thanks! This will definitely be helpful for further development of the code base.
