### ISSUE TITLE
simnibs v4.0-beta1 shows "3.2.6" as version number

### ISSUE THREAD

**Issue by ulloaa** [simnibs/simnibs#104]
Hello, 

We installed v4.0-beta1 today and noticed the output of `simnibs --version` is `3.2.6`. Hopefully it is just the version file that has not been changed?

Thanks!

**Comment by ulloaa** [comment]
Actually, on a second look, I noticed you did change the `_version.py` file to `4.0.0`. We installed directly from your releases page:
```
https://github.com/simnibs/simnibs/archive/refs/tags/v4.0-beta1.tar.gz
```
which is from March 18.

**Comment by oulap** [comment]
The official version is released now. The version tag should now be updated.

The charm command will be available after you install simnibs.
