### ISSUE TITLE
How to do TI simulation

### ISSUE THREAD

**Issue by xiberJ** [simnibs/simnibs#109]
Hello, thank you very much for developing this software, there is a lot to learn
I would like to ask how to complete TI simulation in simnibs. I seem to have seen a TI simulation code, but the input current in it seems to have no relationship with frequency, nor is it in the form of alternating current.
thank you

**Comment by Kstoffer** [comment]
Indeed the spatial distribution of the E-field will not depend on the frequencies, rather the envelope will just be relation to the intensities of the individual simulation like in the code (see Grossmann paper). There is no reason to put in the frequency as this will simply determine the frequency of the envelope but not the spatial distribution.
Best,
Kristoffer

**Comment by 784622315** [comment]
Hello, I am also learning TI, have you solved this problem?Thank you very much

**Comment by oulap** [comment]
You can have a look at this paper to see how to do TACS simulation:

https://www.sciencedirect.com/science/article/abs/pii/S1053811917307723

I'm not entirely sure what you mean by the file about finite element calculation. If you mean how the mesh itself is constructed you can have a look at this function:

https://github.com/simnibs/simnibs/blob/master/simnibs/mesh_tools/meshing.py#L1466

If you mean the simulation, please see here:

https://github.com/simnibs/simnibs/blob/master/simnibs/simulation/fem.py#L1274

**Comment by xiberJ** [comment]
> Hello, I am also learning TI, have you solved this problem?Thank you very much
The program follows the quasi-static principle and cannot set the difference frequency in TTIS
