### ISSUE TITLE
error : Installing SimNibs on WLS 

### ISSUE THREAD

**Issue by tmedani** [simnibs/simnibs#11]
Dear SimNibs team, 

After a successful installation on windows and good results using the headreco 
I want to try the dwi2con.

I have the windows 10 with  Subsystem for Linux (WSL)

For WSL I download the Linux version and ran the following commands :
cd ~/Downloads
tar -xzf install_simnibs_linux.tar.gz
install_simnibs/install_simnibs

after a while, I got this error. 

Do you have any idea how to fix it?

![image](https://user-images.githubusercontent.com/37831900/65546417-19975e80-dedd-11e9-88cd-f94db3e9cdfd.png)

[ simnibs_installer ]CRITICAL: Error executing command: "/home/medani/SimNIBS/miniconda3/bin/../envs/simnibs_env/bin/postinstall_simnibs"  -d "/home/medani/SimNIBS" --copy-matlab --setup-links
[ simnibs_installer ]CRITICAL: Uncaught exception
Traceback (most recent call last):
  File "install_simnibs.py", line 731, in run
  File "install_simnibs.py", line 727, in run
  File "install_simnibs.py", line 451, in run_install
  File "install_simnibs.py", line 337, in _run_postinstall
  File "install_simnibs.py", line 370, in run_command
OSError: Error executing command: "/home/medani/SimNIBS/miniconda3/bin/../envs/simnibs_env/bin/postinstall_simnibs"  -d "/home/medani/SimNIBS" --copy-matlab --setup-links

Thanks in advance.

Best regards

**Comment by guilhermebs** [comment]
Please just try to install again, but uncheck the "Add SimNIBS shortcut Icons" checkbox in the post-install menu

**Comment by tmedani** [comment]
> Please just try to install again, but uncheck the "Add SimNIBS shortcut Icons" checkbox in the post-install menu

Super thank you.
