### ISSUE TITLE
Generating individual tissue .stl files from .msh

### ISSUE THREAD

**Issue by itsyuchao** [simnibs/simnibs#111]
Hello SimNIBS team,  
It seems like charm in 4.0 no longer automatically generates individual tissue .stl files and I'm having trouble extracting them from the .msh file. I couldn't locate any commands (e.g. [here](https://simnibs.github.io/simnibs/build/html/documentation/python_lib/python_lib.html)) that exports .stl based on the labels in .msh.opt. Could you provide some help? 
Thanks a lot and thank you for this great program!
Yuchao

**Comment by TorgeW** [comment]
Hey Yuchao

STL files can be exported using the "write_stl" function from "mesh_io.py"
 
A little example:
```
import simnibs
from simnibs import mesh_io

head_model : simnibs.Msh = simnibs.read_msh('path/to/file.msh')

tissue_tag = 1001 
head_model = head_model.crop_mesh(tags=[tissue_tag])

mesh_io.write_stl(head_model, 'test.stl')
```

**Comment by itsyuchao** [comment]
The code worked great - thank you! 

A follow-up question - is there a way to generate cavities and ventricles? I can combine compact and spongy bone for bone but I don't see cavities and ventricles as physical surfaces in msh file. 

Best,
Yuchao
