### ISSUE TITLE
How to conduct TACS simulation?

### ISSUE THREAD

**Issue by xiberJ** [simnibs/simnibs#112]
Can the program implement Tacs emulation? Does frequency have an effect on stimulus outcome?

**Comment by oulap** [comment]
Please see the FAQ here:
 
https://simnibs.github.io/simnibs/build/html/faq.html

and this paper for more information:

https://www.sciencedirect.com/science/article/abs/pii/S1053811917307723?via%3Dihub

I'll close this issue but feel free to re-open if you have more questions.

**Comment by xiberJ** [comment]
> 请在此处查看常见问题解答：
> 
> https://simnibs.github.io/simnibs/build/html/faq.html
> 
> 和本文了解更多信息：
> 
> https://www.sciencedirect.com/science/article/abs/pii/S1053811917307723?via%3Dihub
> 
> 我将关闭此问题，但如果您有更多问题，请随时重新打开。

Thank you very much for your answer. I would like to know whether the frequency of input current has any influence on the result. According to the FAQ, if different frequencies of stimulation are set, only the speed (frequency) of electric field changes, right?

**Comment by oulap** [comment]
The  frequency of the input current determines how fast the electric changes direction as you say. Roughly, at one time point the current is running from electrode 1 to electrode 2, while in the opposite phase (timepoint) the current is running from electrode 2 to electrode 1, and thus the direction of the electric field is opposite to timepoint 1. We do not have models of how different frequencies affect neurons or stimulation outcomes.
