### ISSUE TITLE
`Magstim_70mm_Fig8.nii.gz` should probably just be removed in favour of the .ccd file

### ISSUE THREAD

**Issue by seanm** [simnibs/simnibs#114]
Between SimNIBS 3.2.5 and 4.0 the file `MagVenture_MC_B70.nii.gz` was removed in favour of the .ccd file.

The only .nii.gz coil file that's left is `Magstim_70mm_Fig8.nii.gz`.  You may as well remove it too (in favour of the .ccd file).

**Comment by TorgeW** [comment]
Thanks for your feedback, we are aware of this.
We decided to keep the .nii.gz file in this case because it is used in this tutorial:
https://simnibs.github.io/simnibs/build/html/tutorial/gui.html
