### ISSUE TITLE
Labels of the tissues in the msh files?

### ISSUE THREAD

**Issue by ftadel** [simnibs/simnibs#116]
Where can we get the correspondence between the tissue indices (tetrahedron_regions) and the labels?
Does CHARM always use the same index for a give tissue type?

**Comment by oulap** [comment]
Yes the correspondence is always the same. You can look at the tissue color table (final_tissues_LUT.txt) to see the tissue labels. The volume elements have the same labels and surface are labeled as 1000 + label.

**Comment by ftadel** [comment]
Thanks!
