### ISSUE TITLE
metrics in ROI 

### ISSUE THREAD

**Issue by ggrrll** [simnibs/simnibs#119]
are there implemented metrics in the ROI ?  (in particular for distributed optimization)

thanks

**Comment by oulap** [comment]
Here's a description of the metrics used in the distributed optimization:

https://simnibs.github.io/simnibs/build/html/_downloads/3857e582cbbe9350fe7e836b379235c1/ERNI_opt.pdf

**Comment by ggrrll** [comment]
thanks -- my Question  was more about python API : 

how to get final metrics in ROI (opt.target_image) or if it's possible to get the post-opt field and currents, so that one can define custom metrics, in ROI

Thanks

**Comment by ggrrll** [comment]
I computed some metrics from the msh files -- thanks
