### ISSUE TITLE
Optimsation without considering the direction normal to the surface in Distributed target opt

### ISSUE THREAD

**Issue by AndreasGkatz** [simnibs/simnibs#123]
Dear SimNibs team,

I was wondering if it is possible to optimise for electric field magnitude, instead of normal to the surface, when using the distributed target optimisation, like there is an attribute in TDCStarget to set the directions to 'None'.

Info that could be relevant for a valuable feedback:
I use a binary image of a grey matter segment (e.g. angular gyrus) as the target.
I tried to give a high value (100) to the target_intensity (as suggested ([here](https://simnibs.github.io/simnibs/build/html/tutorial/optimization.html)))but it did not give the desired results (still optimising based on normal). 
Leadfield was calculated with the default options.

 
 Thank you in advance for your time.
 
 Best regards

**Comment by oulap** [comment]
The magnitude option is not implemented for the distributed optimization. You can only optimize with the normal component.
