### ISSUE TITLE
target_map in distributed target opt

### ISSUE THREAD

**Issue by AndreasGkatz** [simnibs/simnibs#124]
Dear SimNibs team,

I was wondering if you could give me some clarification on these 2 questions:

 Does the TDCSDistributedOptimize treat these two scenarios the same way?
 - Target image with target voxel values = 100 and 0 elsewhere and target_intensity = 1
 - Target image with target voxel values = 1 and 0 elsewhere and target_intensity = 100 
 
 
 What type of interpolation is used to trasfer the nifti target data to the msh format?
 
 (Note: I am not using T_maps as inputs, but segment selections based on Freesurfer's recon-all segmentations)
 
 Best regards

**Comment by oulap** [comment]
It should affect the solution, but in your case it might not be a drastic change as you're setting the values outside the target to zero. You can find documentation on the distributed optimization problem here:

https://simnibs.github.io/simnibs/build/html/_downloads/3857e582cbbe9350fe7e836b379235c1/ERNI_opt.pdf

in eq. 5 y is the target intensity multiplied by the weight map and W is the weight map, see here:

https://github.com/simnibs/simnibs/blob/master/simnibs/optimization/opt_struct.py#L2246

the weighting between the terms in eq.7 would then be different.

**Comment by oulap** [comment]
Closing this one, feel free to open if you have further questions.
