### ISSUE TITLE
Error with downloading SimNIBS 4.0_ windows_ installer

### ISSUE THREAD

**Issue by Xiaoheymore** [simnibs/simnibs#125]
Hi,
I've tried many times, but still fail to download the latest 4.0. from https://simnibs.github.io/simnibs/build/html/installation/simnibs_installer.html 
. Is this because of my personal networks ?

**Comment by oulap** [comment]
We've had some problems with the server hosting the user registration, but you can gran the installer from here:

https://github.com/simnibs/simnibs/releases/tag/v4.0.0
