### ISSUE TITLE
dwi2con & conductivity tensor

### ISSUE THREAD

**Issue by tmedani** [simnibs/simnibs#13]
Dear SimNibs team, 

I'm trying to use and understand the dwi2cond process. 
First of all, thanks for this great job, all the complex computation steps are summarized in ONE function, this is really great as the headreco function. 

My questions are: 
In this page (https://simnibs.github.io/simnibs/build/html/documentation/command_line/dwi2cond.html)
you said:... to estimate conductivity tensors for GM and WM. The following mappings from diffusion to conductivity tensors are supported: ...
and then you listed a couple of methods that are used. 

1- Does dwi2con combine all these methods or there is an option to specify which method to use? 

2- The outputs files of dwi2con are stored on the d2c_SubjectID, is there any further documentation which explains the different output files stored in this folder. 
(I was able to understand some of them.) 

3- Related to the Q2, I found the DTI tensor here: d2c_ernie\dti_results_XX\DTI_conf_tensor.nii.gz
but I can not find where the conductivity tensors are stored, 
Could you help me with that?

4- I was able to visualize the  "first_ev_for_check.msh"
but I did not understand what are the displayed lines?

![image](https://user-images.githubusercontent.com/37831900/68987623-e09aac80-07f0-11ea-8d25-267a044b5a21.png)

Are they the diffusion tensors or the conductivity tensors? 

Since you display only one vector, is it the max eigenvalue vector?

How did you do to map the tensor value from voxel to tetra? 

Sorry for my many questions, and thanks again for your help. 

Kind regards 
Takfarinas

**Comment by guilhermebs** [comment]
Hi,

Thanks for your continuous interest in SimNIBS! In fact this information is missing from the documentation.

1- After dwi2cond, the tensors are stored in a format such that we can calculate the the "dir", "vn" and "mc" conductivity on the fly. So those are only computed right before the FEM simulation. You can see the calculation code  [here](https://github.com/simnibs/simnibs/blob/761a491ff34cde3ab6e2a29e7a424eeef89daf19/simnibs/simulation/cond.py#L101), which implements (with some small modifications) the procedure described [here](https://www.pnas.org/content/98/20/11697)

2- The only output that really matters is the "DTI_conf_tensor.nii.gz" file. It is the only one we use for calculations.

3- The tensors are stored for GM and WM voxels. The file has 6 volumes, which correspond to the values of the 3x3 symmetric matrix which is the conductivity tensor. They are organized in the following way:
I[0] I[1] I[2]
I[1] I[3] I[4]
I[2] I[4] I[5]


4- Those correspond the the largest eigenvector of the conductivity tensor in each tetrahedron, scaled by it's engenvalue. It gives an idea of the "preferential direction" of the current flow. If you clip the model you should be able to for clearly see the fiber bundles in the corpus callosum for example.

**Comment by tmedani** [comment]
Dear @guilhermebs, 

Thank for these explanations. 

1- I will try to understand the code & this paper asasp. 
What do you refer to "dir", "vn" and "mc" ? are they explained on the paper? 

2- you mean that the values stored in this file are not the final value for the conductivity tensor ?? 

3- 
> 3- The tensors are stored for GM and WM voxels. The file has 6 _**volumes**_,....

Did you mean 6 values per volume? 

The rest is clear, :)

4- Yes, make sense, and the GMSH display is good as well. Thanx

Thanks again for your answer,

Kind regards 
Takfarinas

**Comment by guilhermebs** [comment]
1- I think [this paper ](https://doi.org/10.1016/j.neuroimage.2011.06.069) explains better this aspect. 
* dir -> direct mapping. We get both tensor volumes and directions from data
* vn -> volume normalized. All the tensors are normalized to have the same volume.
* mc -> mean conductivity. Not actually anisotrpic. We only get the tensor volumes but not their direction

2 - Yes. Those are not the final conductivity values.

3- Well, both are equivalent.


Best,
Guilherme

**Comment by tmedani** [comment]
@guilhermebs thank you for these explanations. 
We will have a look at that.
