### ISSUE TITLE
libm.so.6: version `GLIBC_2.23' not found

### ISSUE THREAD

**Issue by cascam07** [simnibs/simnibs#138]
Hello, I recently installed SimNIBS4.0 for my profile in a shared Linux environment, using the Linux installer. The GUI works fine and I was able to successfully run charm on one of our datasets, but I haven't been able to get gmsh to work in order to visualize the results. At first, when I tried to run gmsh, I got the following:

```
gmsh: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by gmsh)
gmsh: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by gmsh)
gmsh: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by gmsh)
gmsh: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by gmsh)
gmsh: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by gmsh)
```

I was able to address the libstdc++.so.6 errors by preloading the version located in: 
`SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/simnibs/external/bin/linux/`

However, there doesn't appear to be any included version of libm.so.6 I could apply a similar trick to, so I'm still stuck with: 
``` gmsh: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by gmsh) ```
Do you have any suggestions for how I can sort out these dependency issues with gmsh?

Thank you!
-Cameron

**Comment by oulap** [comment]
Hi,

This seems to be a gmsh issue, see here:

https://gitlab.onelab.info/gmsh/gmsh/-/issues/2330

You probably need to either get the correct version of the system libraries and make sure gmsh is using the correct one, or compile gmsh from scratch. 

Which Linux are you running? We build on centos7 and test on centos7, ubuntu 20.04 and ubuntu 22.04. The test do not check for gmsh compatibility, but gmsh should also run on those systems.

**Comment by oulap** [comment]
Hmm, it's a bit tricky if you don't have control over the system libraries. I've managed to compile stuff by installing compilers through conda:

`conda install -c conda-forge gxx_linux-64=7.5 gcc_linux-64=7.5 sysroot_linux-64=2.17`

and then linking to those in the build. It's not the newest gcc but maybe it will do the trick.
