### ISSUE TITLE
v3.1 bug fem.tms_coil called with incorrect # of args

### ISSUE THREAD

**Issue by jerdra** [simnibs/simnibs#15]
Just reporting an observation that the calling function of fem.tms_coil in TMSLIST wasn't updated to pass in a solver. 

Instead the cpus variable gets passed into fem.tms_coil's solver option and n_workers stays as the default=1.

**Comment by guilhermebs** [comment]
Thanks a lot for the heads up! Solved in 3b57d00cd5f3b91d3edcac4e83e368e1e620b648
