### ISSUE TITLE
With version 4.0.1, conda installation fails

### ISSUE THREAD

**Issue by ualsbombe** [simnibs/simnibs#152]
pip install https://github.com/simnibs/simnibs/releases/tag/v4.0.1

![image](https://github.com/simnibs/simnibs/assets/17312936/5ebd7048-68fd-4709-a2d9-4a497e7539ca)

Instructions from here, https://simnibs.github.io/simnibs/build/html/installation/conda.html , have been followed with no errors or warnings until this point

**Comment by oulap** [comment]
Try giving the full path to the wheel file, i.e., 

pip install https://github.com/simnibs/simnibs/releases/download/v4.0.1/simnibs-4.0.1-cp39-cp39-linux_x86_64.whl

for the linux wheel.
