### ISSUE TITLE
Using Freesurfer / FSL results as input for mri2msh

### ISSUE THREAD

**Issue by vferat** [simnibs/simnibs#16]
Hi,

I would like to know if it is possible to use the result of a freesurfer recon all to initialize the mri2mesh script ? 
In my case, I'v already compute the recon-all for all my subjects, and it seems quiet useless to redo it during the mri2mesh reconstruction...

Same for FSL FLIRT/FNIRT,  would it be possible to initiate the mri2mesh algorithm with the FSL results ?

Thanks for you help and you amazing work on this software !

**Comment by vferat** [comment]
btw, the idea behind this would be to use simnibs in different [nipype](https://github.com/nipy/nipype) workflows.

**Comment by guilhermebs** [comment]
Sorry for the late answer.
Unfortunately this is not possible, as we need to do some preprocessing to make sure that both the FreeSurfer and FSL steps are performed in the same space and aligned with each other.
