### ISSUE TITLE
High CPU use during charm meshing in python 3.9.17

### ISSUE THREAD

**Issue by jhouck** [simnibs/simnibs#166]
This is in the 4.0.1 development version, cloned yesterday, in ubuntu 18.04 LTS. During meshing (display says [ simnibs ]INFO: Meshing, Began meshing, Lloyd, Perturb, Exude) charm is using 38-39 of 40 cores (e.g., top currently shows charm at 3952 %CPU). I have not changed the default threads=8 in charm.ini and OMP_NUM_THREADS is 10. 

Is there some other way to limit charm's CPU use, short of setting up a docker container or running via taskset?

**Comment by oulap** [comment]
charm uses cgal for the meshing, which again uses TBB for threading, so OMP environment variables won't work unfortunately. The thread number in the settings file controls the parallelization of the segmentation part of charm not the meshing. Long story short, at the moment there's no easy way to control the number of threads the meshing part uses, but I agree that hogging all the cores is not nice behavior.

I guess the best solution would be to pass the threads variable to cgal, which requires some minor changes in the source code. I'll put that on the todo list.

**Comment by jhouck** [comment]
Great, thank you. I'll try setting up a docker container for now, taskset was not helpful in this case.

**Comment by jhouck** [comment]
Here's a gist of the Dockerfile in case it's useful to anyone else: https://gist.github.com/jhouck/ae2c3c6b35b558c420155216de2518e7  .  To limit CPU use during meshing `--cpus` should be set to some reasonable number in the `docker run` command line.  Output goes to whatever you use for `--workdir`.  There's no entrypoint, charm is in the container's path, so just append your charm commands after whatever image:tag combination you named the image.

**Comment by oulap** [comment]
Thanks! I also sorted this out in SimNIBS so now the number of threads you set in the charm.ini or settings.ini is also respected by the meshing. The fix will be included in the next release.
