### ISSUE TITLE
Headreco mesh on defaced MRI

### ISSUE THREAD

**Issue by tmedani** [simnibs/simnibs#17]
Dear SimNibs team, 

We are still working on your tools :)

I'm trying to test headreco on defaced  MRI (anonymised), we have only the T1 data.
It works fine, however, I was surprised about the final mesh.
![image](https://user-images.githubusercontent.com/37831900/73416737-bd00e180-42ca-11ea-8736-20808a7a2119.png)

I was expecting to have a hole on the mesh. 

Is there any coregistration to a template that introduce modification on the input?  

Thanks in advance for your help.

Best Regards 
Takfarinas

**Comment by oulap** [comment]
Hi Takfarinas,

The missing part, i.e., the face in this case, is reconstructed from the anatomical prior used in the segmentation. In this sense it's  a "standard face", which replaces the missing face.

Best,
Oula

**Comment by tmedani** [comment]
Hi Oulap,
Thanks for your answer. 

> "standard face"

From where do you get this standard face?
 Is it the MNI model? 

The replaced of the missing face, does it replaced only by the skin or it can replace any other tissue? 
What may happen if the removed part of the MRI affects the bone for example? 

We really appreciate your work and your answers. 
Thank you. 
Best,
Takfarinas

**Comment by oulap** [comment]
Hi Takfarinas,

The face is not filled in from the standard MNI template, but a probabilistic tissue prior (or a tissue probability map (TPM)) which is deformed to match the input MRI during segmentation. 

Some details on the tissue prior can be found here: Huang et al. Automated MRI segmentation for individualized modeling of current flow in the human head, Journal of Neural Engineering, 2013.

All missing values, i.e., voxels with zero values, will be filled in from the prior. So if you would remove half the brain, the algorithm would fill in the missing part based on the prior. Obviously, this is a very crude approximation of the missing values. 

Best,
Oula

**Comment by tmedani** [comment]
Super @oulap 
Thank you for your clear answers.
