### ISSUE TITLE
Scalp to Cortex Distance

### ISSUE THREAD

**Issue by amayeli** [simnibs/simnibs#18]
Hello,

I have two question. I would greatly appreciate it if you could help me with those
1- I would assume the main factor for calculating E-field after selecting the TMS intensity and location is the scalp to cortex distance and cortex thickness. Is that correct, or there are more main factors?
2- I was wondering if there is a way to get the scalp to cortex distance (and possibly the cortex thickness) for the point that we select for stimuli in SimNIBs. If not, do you know any other software/tool that I could use to get those measures.

Thank you for your help in advance and for providing such a great software

**Comment by guilhermebs** [comment]
Hi,

Thanks for the interest in SimNIBS!

You are right that scalp-cortex distance is an important factor for TMS field strength, but it is far from the only one. [Please see this paper for a more detailed study about TMS electric fields](https://doi.org/10.1016/j.neuroimage.2010.07.061), things like coil direction with respect to the giral folding also matter a lot. And the only way to obtain good estimates of the electric field values is to run a complete simulation in an accurate head model.

We do not offer any "out-of-the-box" tools for calculating coil-scalp distances, but it can be done with a bit of code. I would do the following:
1- Calculate the baricenters of the cortex/scalp surface triangles
2- Calculate the distance between the 2 surfaces using KDTrees (implemented in SciPy and Matlab)

**Comment by amayeli** [comment]
Hi Guilherme,

Thank you very much for your prompt reply!  Could you please guide in which script in SimNIBs Package I can make the modification to calculate barycenters of cortex/scalp surface?

Thanks,
Ahmad

**Comment by guilhermebs** [comment]
Are you using python or matlab?

**Comment by amayeli** [comment]
I didn't install simNIBS through Conda, so I'd assume I use MATLAB. I open simNIBS GUI for the analysis. Sorry that I am not sure about it.

**Comment by amayeli** [comment]
By the way, I think all I nee

**Comment by guilhermebs** [comment]
If you set-up a TMS simulation and select the coil center in the brain, SimNIBS will automatically correct it for the closest scalp position. Please see:
MATLAB:
 https://github.com/simnibs/simnibs/blob/master/simnibs/examples/simulations/TMS_MNI.m
Python:
https://github.com/simnibs/simnibs/blob/master/simnibs/examples/simulations/TMS_MNI.py

And we also added the TMS optimization feature, which you can see here
https://simnibs.github.io/simnibs/build/html/tutorial/advanced/tms_optimization.html


I initially understood you wanted to calculate the scalp-cortex distance for every point in the cortex, which is way more complicated, but can still be done with some coding in either python or matlab.

Also, SimNIBS installs python for you, you don't need to install it through conda to have access to the python interface.

**Comment by amayeli** [comment]
Thank you for your prompt reply and your great help! 
In the example you provided , we have "S.poslist{1, 1}.pos.pos_ydir" and "S.poslist{1, 1}.pos.centre", which are related to the target on scalp (please correct me if I make a mistake). How I could get the position for the closest gray matter point?

**Comment by guilhermebs** [comment]
1- In the "TMS_MNI" examples, both "centre" and "pos_ydir" are defined in the cortex and in MNI coordinates.

2- Why do you want to measure distance from a scalp position to the closest gray matter point? To place the coil, we normally do the opposite (define a cortex position -> get the closest scalp position).

**Comment by amayeli** [comment]
1- Do we have the scalp coordinate (closest scalp position)?
2) I just need the distance from cortex to scalp. I didn't know it is the other way around. Is there any way to measure that based on what you mentioned (define a cortex position -> get the closest scalp position)?

Thanks!
Ahmad

**Comment by guilhermebs** [comment]
I'm sorry, I don't fully understand which data do you have and what do you want to do with it.

If you just want to calculate distances, the easiest way is to load the mesh in python/matlab and use native python/matlab functions. Please see the examples
https://github.com/simnibs/simnibs/blob/master/simnibs/examples/analysis/roi_analysis_mni.m
and
https://github.com/simnibs/simnibs/blob/master/simnibs/examples/analysis/roi_analysis_mni.py

they do not do exactly what you want but should give you a good idea of how to do it.

**Comment by amayeli** [comment]
I am sorry for confusing you. I simply need the distance between the cortex and scalp (or stimulating coil). The examples you provided, give us the coordinates for gray matter (cortex), but for calculating the distance, we need the scalp coordinates as well. Do we have the scalp coordinates as well as gray matter positions in those examples? If so, would you please let me know which variables are those?
Thanks,
Ahmad

**Comment by guilhermebs** [comment]
To get a list of position in the scalp and in GM,  you can use
``` python
scalp_surf = head_mesh.crop_mesh(1005)
scalp_pos = scalp_surf.nodes[:]

gm_surf = head_mesh.crop_mesh(1002)
gm_pos = gm_surf.nodes[:]
```
or in MATLAB
```matlab
scalp_surf = mesh_extract_regions(head_mesh, 'region_idx', 1005);
scalp_pos = scalp_surf.nodes

gm_surf = mesh_extract_regions(head_mesh, 'region_idx', 1002);
gm_pos = gm_surf.nodes
```

**Comment by amayeli** [comment]
Hello Guilherme,

Thank you for helping me with getting the list of gm/scalp positions. I was able to calculate the scalp to cortex distance using what you suggested earlier ( Calculate the barycenters first and then use KDtree in MATLAB). My only concern is that the coordinates on SimNIBS GUI looks different from what I get out of  
gm_surf = mesh_extract_regions(head_mesh, 'region_idx', 1002);
I just used 
scatter3(gm_surf.nodes(:,1),gm_surf.nodes(:,2),gm_surf.nodes(:,3))
to visually compare the SimNIBS GUI and MATLAB plot (however it's a little bit difficult to compare precisely). For instance if I go to (-40, -20,  40) on SimNIBS and trying to go to the same position in MATLAB  scatter plot, they look different. Do you have any suggestion about that? Are they supposed to be the same?

Thanks,
Ahmad

**Comment by guilhermebs** [comment]
Hello,

In the GUI you can only pick positions in the scalp surface. So if you input a position that is in the cortex, it will be projected to the closest point in the scalp surface.

Best,
Guilherme
