### ISSUE TITLE
Controlling the volume mesh density with headreco

### ISSUE THREAD

**Issue by tmedani** [simnibs/simnibs#19]
Dear SimNibs team, 

I would like to know if there is a possibility to control the volume mesh density.

From my understanding the -v option of headreco control the surface mesh density and not the volume. 

Here is an example :
The triangles on the surfaces are smaller than those on the volume 
 
![image](https://user-images.githubusercontent.com/37831900/74266220-c4f05680-4cb8-11ea-9cd9-fb2b2d977cf9.png)
![image](https://user-images.githubusercontent.com/37831900/74266242-d174af00-4cb8-11ea-87be-4b3a38d2e6e1.png)

Is it possible to change the mesh density of the tetra?

**Comment by guilhermebs** [comment]
Hello,

Yes, there should be a couple of ways of doing this.
If you already have a mesh, you can refine the mesh by running
`gmsh -refine input.msh -o output.msh`
Beware that this will increase the number of tetrahedra by around 8x

If you want to change the meshing procedure, you might want to change this function:
https://github.com/simnibs/simnibs/blob/6a52c56ba93d8f11e6c7764721bcd5aa9b12709e/simnibs/msh/headreco.py#L1711
and change the Gmsh configurations.

**Comment by tmedani** [comment]
Thank you @guilhermebs 
I will have a look in deep and find an interactive option to change this parameter. 

Best
