### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by JiupengXiong** [simnibs/simnibs#197]
Hi, Engineer. I'm a biomedical researcher from China. I want to consult some issues about SimNIBS's installation. The pop-up displays that there was an error when installing SimNIBS. The detail is as follow: 
[InstallingError.txt](https://github.com/simnibs/simnibs/files/12574334/InstallingError.txt)
I hope you can provide a effective technical support about SimNIBS's installation. thanks！

**Comment by TorgeW** [comment]
If possible please install powershell.exe and try again :)
