### ISSUE TITLE
Clicking on "Gray Matter" with empty project creates infinite loop

### ISSUE THREAD

**Issue by vfonov** [simnibs/simnibs#2]
Clicking on "Gray Matter" with empty project creates infinite loop showing Error message "argument 1:<class 'Type Error'>: wrong type and on console the message "QWidget::repaint: Recursive repaint detected" is printed.

See attached screenshot 
<img width="1200" alt="Screen Shot 2019-06-27 at 10 46 11 AM" src="https://user-images.githubusercontent.com/628822/60276191-2817af00-98c9-11e9-8d50-4e9740f30f6b.png">

**Comment by guilhermebs** [comment]
Fixed by a41bd58e599e3ad5d7f22b17ab7c5d5f9257a227
