### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by xiberJ** [simnibs/simnibs#218]
[install.log](https://github.com/simnibs/simnibs/files/13162583/install.log)
![1698218801118](https://github.com/simnibs/simnibs/assets/122353886/815202e7-6f3b-4f36-a51e-acb581caad1d)
Dear developers, I used to be able to open the gui and Windows shortcuts normally, until recently I found that I could not open the 4.0.0 version, and then reported an error as described in the file.
thank you

**Comment by xiberJ** [comment]
> 嗨,我最近在安装Simnibs(或者更确切地说是在运行时)时遇到了类似的错误。它让我有点困惑,因为它似乎只发生在PETCS模块--而且只是有时候。但是,从pydn3.8开始,DLL模块加载被修改为使用代码。[ 克兰奇](https://docs.python.org/3/library/ctypes.html#module-ctypes) 包装C代码。我们的PETCS模块使用CINT,而我们拥有的其他模块(它包了C/C++代码)则使用YYTAN。很明显,以前的行为是不稳定和不安全的,这就是为什么这种改变。我们正在制作下一个Simnibs版本的预发布版本,我将在我的端添加什么可以解决这个问题(这是用来使用的)。`os.add_dll_directory` 而不是增加路径)。
> 
> 一旦修复被引入到下一期的Simnibs版本中,我会告诉你(希望能在几天内完成)。
> 
> 这也应与[ 这个](https://github.com/simnibs/simnibs/discussions/162#discussion-5365649) 讨论。
> 
> 最好的, 杰斯帕

Thank you very much for your response. I would like to ask if it is possible for me to use previous software versions to avoid this problem. This situation exists in both 4.0.0 and 4.0.1, and I have used 4.0.0 for a long time. I spent a long time trying to install the method but this problem came up

**Comment by jduemose** [comment]
Hi @xiberJ @divyarajasekharan

We have a pre-release of simnibs 4.1 out now. You are welcome to try that out and see it is helps with your issue. You can find it on the release page.

Best,
Jesper

**Comment by zhangbeijing2024** [comment]
Hi @xiberJ 
I have encountered the same error when trying to install simnibs4.0.1. Have you solved this problem? 
Thank you.

**Comment by jduemose** [comment]
@zhangbeijing2024 did you try the new pre-release (version 4.1*)? You can find it on the release page just below v. 4.0.1

**Comment by zhangbeijing2024** [comment]
> @zhangbeijing2024 did you try the new pre-release (version 4.1*)? You can find it on the release page just below v. 4.0.1
![image](https://github.com/simnibs/simnibs/assets/155703290/e7df0434-ca94-425a-88aa-27871d1915fc)
Unfortunately, I still encountered this error.

**Comment by xiberJ** [comment]
> 你好@xiberJ 我在尝试安装simnibs4.0.1时遇到了同样的错误。你解决了这个问题吗？ 谢谢。

没有，我是一台新电脑上使用的，我原本电脑先前第一次装没有问题，后面重装一次就出现了，win系统
No, I use it on a new computer. There was no problem with the first installation of my original computer, but after the first reinstallation, the win system appeared

**Comment by zhangbeijing2024** [comment]
> > 你好@xiberJ 我在尝试安装simnibs4.0.1时遇到了同样的错误。你解决了这个问题吗？ 谢谢。
> 
> 没有，我是一台新电脑上使用的，我原本电脑先前第一次装没有问题，后面重装一次就出现了，win系统 No, I use it on a new computer. There was no problem with the first installation of my original computer, but after the first reinstallation, the win system appeared

yes. I successfully installed version 4.1 on a computer that has never installed SimNIBS before, but it cannot be successfully installed on a computer that has been installed before.
