### ISSUE TITLE
Enhancement request: provide coil definition file for Nexstim 5.0 cooled coil

### ISSUE THREAD

**Issue by DavidEWarrenPhD** [simnibs/simnibs#22]
It would be terrific if a coil definition file could be provided for the Nexstim 5.0 air-cooled coil.

**Comment by guilhermebs** [comment]
Unfortunately we do not have access to this coil, so we likely will not add it in the near future.

**Comment by guilhermebs** [comment]
Please contact us via support@simnibs.org, we will answer you over there
