### ISSUE TITLE
Problem with T2_reg.nii.gz file

### ISSUE THREAD

**Issue by carenlat** [simnibs/simnibs#232]
Hello, 

I have a problem with the following command:

__

C:\Users\latreche\Desktop\7524\simnibs> charm 7524 org\sub-7524V1_T1.nii org\sub-7524V1_T2.nii --forceqform
[ simnibs ]INFO: simnibs version 4.0.1
[ simnibs ]INFO: charm run started: Tue Nov  7 11:40:42 2023
[ simnibs ]INFO: Reading settings from C:\Users\latreche\SimNIBS-4.0\simnibs_env\Lib\site-packages\simnibs\charm.ini
[ simnibs ]CRITICAL: Uncaught exception
RuntimeError: C:\Program Files (x86)\ITK\include\ITK-4.13\itkImageFileReader.hxx:143:
 Could not create IO object for reading file C:\Users\latreche\Desktop\7524\simnibs\m2m_7524\T2_reg.nii.gz
The file doesn't exist.
Filename = C:\Users\latreche\Desktop\7524\simnibs\m2m_7524\T2_reg.nii.gz

___

The folder m2m_7524 was created with this command, but indeed the T2_reg.nii.gz file was not created, therefore it does not exist.
Does anyone has an idea on what I could do to solve this error ?

Thanks,

Caren

**Comment by bjornsig** [comment]
Hi, can you try to use the pre-release? you can find it here https://github.com/simnibs/simnibs/releases/tag/dev
