### ISSUE TITLE
Warped TMS coil

### ISSUE THREAD

**Issue by SVH35** [simnibs/simnibs#236]
Dear SimNIBS team

When running TMS simulations using a SimNIBS 4.0.1 mesh and TMS poslist, in 1 out of 16 subjects, the coil is warped and therefore, the E-field results invalid:

<img width="612" alt="image" src="https://github.com/simnibs/simnibs/assets/88398607/1c772e2e-3a0a-4d4f-a355-3f1e7389026b">

I could not find the cause of this bug. Things I tried, to no avail:
(1) Changing the coil type
(2) Changing the coil position
(3) Rerunning CHARM

**Comment by TorgeW** [comment]
Can you provide the pos list (.mat file) so we can check out what happened here?

**Comment by SVH35** [comment]
Sure thing! Here is the pos list, I added it as .pkl.zip file since I ran it in python. 

[poslist.pkl.zip](https://github.com/simnibs/simnibs/files/13365296/poslist.pkl.zip)

**Comment by TorgeW** [comment]
the .mat file for the pos list is written in the simulation output folder no matter if you use python or matlab :)

**Comment by SVH35** [comment]
My bad, thought you meant the pos list that is submitted when calling run_simnibs(). Anywat, here is the .mat pos list (output). 

[simnibs_simulation_20231115-143917.mat.zip](https://github.com/simnibs/simnibs/files/13365441/simnibs_simulation_20231115-143917.mat.zip)

**Comment by SVH35** [comment]
Problem was related to used neuronavigation coordinate file, with a shearing component being present in the file.

Using a different coordinate file and https://simnibs.github.io/simnibs/build/html/documentation/neuronavigation/localite.html , the problem is no longer 🙂
