### ISSUE TITLE
Scripting tDCS (without TMS) simulations in MATLAB

### ISSUE THREAD

**Issue by giadadamiani** [simnibs/simnibs#25]
Hi! I am using the MATLAB script you made available [here](https://simnibs.github.io/simnibs/build/html/tutorial/scripting.html) to run simulations from MATLAB. This includes tDCS and TMS simulations. We are only interested in tDCS. I tried to comment out the TMS section, but the function run_simnibs(s) seems to require inputs from the TMS setup. Is there a way to only run tDCS simulations from MATLAB? Thank you!

**Comment by guilhermebs** [comment]
Hello,

Sure! You just need to define a TDCSLIST structure. Please check out or [examples](https://github.com/simnibs/simnibs/blob/master/simnibs/examples/simulations/tDCS.m)

Best Regards,
Guilherme

**Comment by giadadamiani** [comment]
This works perfectly, thank you!
