### ISSUE TITLE
Python : electrode

### ISSUE THREAD

**Issue by KOOLAB1** [simnibs/simnibs#254]
In the electrode method, multiple electrodes will be placed. Can I change the color to distinguish this? It can customize the shape, but I want to change the color.

**Comment by TorgeW** [comment]
I assume that you mean the color in gmsh.
In gmsh you can select to only visualize the electrodes and for example the skin (Tools -> Visibility):
Then you can go to the color settings (Tools -> Options -> Mesh -> Color) and set the color for different tags.
Please note that you have to deselect any views (e field data) and (Tools -> Options -> Mesh -> Visibility -> Enable 2D element faces and 3D element faces).

Please also see our tutorial on visualizing results. 
https://simnibs.github.io/simnibs/build/html/tutorial/visualization.html
