### ISSUE TITLE
leadfield matrix

### ISSUE THREAD

**Issue by OneMore1** [simnibs/simnibs#256]
Hi,

I got leadfield matrix from f['mesh_leadfield']['leadfields']['tdcs_leadfield'] in h5py file which generated by function tdcsleadfield. I found the channel order of the leadfield matrix is inconsistent with the corresponding order in the CSV from eeg_position. For EEG10-10_UI_Jurak_2007.csv, when activating the first channel, the stronger electrical field appears near C3, whereas it should be at Fp1. I am not sure that it is because of my codes or something else. Could you assist in verifying the structure of the leadfield matrix, is the electrode order same to that in csv file.

Best regards,
Mo

**Comment by jduemose** [comment]
Hi Mo

AFAIK the order is the same, yes, however, if a reference channel is not explicitly specified (using the ReferenceElectrode tag in the csv file) then I believe it just uses the first electrode as reference and constructs the leadfield matrix wrt. this electride. This can then be re-referenced later (e.g., to an average reference). Is this consistent with what you observe?

Best,
Jesper

**Comment by OneMore1** [comment]
Hi, @jduemose. 

Thanks for your help. I run the TDCSLEADFIELD with adding codes
```
tdcs_lf.interpolation = None
tdcs_lf.map_to_surf = False
tdcs_lf.tissues = [5]
```
to generate the tetrahedral mesh and the eeg_cap is default which should be EEG10-10_UI_Jurak_2007.csv.

And I used the code to get LFM and POS for the midpoint of the mesh.

```
pos = f['mesh_leadfield']['nodes']['node_coord'] 
pos_index =  f['mesh_leadfield']['elm']['node_number_list'] 
lfm = f['mesh_leadfield']['leadfields']['tdcs_leadfield'] 
new_pos =  np.zeros([lfm.shape[1], 3])
for idx, i in enumerate(pos_index):
    new_pos[idx] = (pos[i[0]-1] + pos[i[0]-1] + pos[i[0]-1] + pos[i[0]-1]) / 4
```

And I visualized the average value of LFM within a 5 mm radius around each electrode. The X-axis represents the activated channel in LFM, while the Y-axis displays values adjacent to corresponding electrodes as per their sequence in the CSV file, excluding fiducial electrodes. I observed that when index 0 on the X-axis (Fp1) is activated, the maximum value appears near index 1 on the Y-axis (Fp2). Conversely, when index 34 on the X-axis (the position of the reference electrode) is activated, the maximum value appears near index 0 on the Y-axis (Fp1). This led me to experiment by placing the values of the index of reference electrode to the forefront., after which I noticed that the maximum value is accurately shown along the diagonal.
![image](https://github.com/simnibs/simnibs/assets/129330534/1cdccde9-d805-4f2e-a5cc-3a911fdac24e)

In the output of [ simnibs ]INFO: Placing Electrode, I found the first channel shown is reference electrode [ 1.9644e-03 -8.2366e+00  9.7152e+01], and the Fp1 [-29.0429  80.7818  -8.6762] shows after C1 which is the position of reference electrode in csv file. The sequence of Fp1 and reference electrode in output is swapped. I'm not sure if this is relevant.
![image](https://github.com/simnibs/simnibs/assets/129330534/cf0967b6-8890-4b50-ae40-a6f32e83051f)

I can provide more code if need, thank you again.

Best,
Mo

**Comment by jduemose** [comment]
I am not sure I follow exactly what the matrix displays although I get that it is a covariance between the electrodes of some sort.

As to your original question: If your goal is to verify the order of the electrodes in the leadfield matrix (or just compare with the order in the csv), then I would probably start by taking a look at `f["mesh_leadfield"]["leadfields"]["tdcs_leadfield"].attrs["electrode_names"]`. This contains the electrode names and I would assume that this is in the order of the channels in the matrix. You can get the name of the reference channel from `f["mesh_leadfield"]["leadfields"]["tdcs_leadfield"].attrs["reference_electrode"]` and check its position in the former array. Does that align with your observations or did you check this already?

You can also add each column (for one direction x/y/z) as ElementData to a mesh of the tissues where the leadfield has been computed (I guess you can use the mesh `{subid}_ROI.msh`) and look at whether it makes sense.

**Comment by OneMore1** [comment]
Hi, @jduemose. 

The results I got from f["mesh_leadfield"]["leadfields"]["tdcs_leadfield"].attrs["electrode_names"] is
```
array(['Cz', 'Fpz', 'Fp2', 'AF7', 'AF3', 'AFz', 'AF4', 'AF8', 'F9', 'F7',
       'F5', 'F3', 'F1', 'Fz', 'F2', 'F4', 'F6', 'F8', 'F10', 'FT9',
       'FT7', 'FC5', 'FC3', 'FC1', 'FCz', 'FC2', 'FC4', 'FC6', 'FT8',
       'FT10', 'T9', 'T7', 'C5', 'C3', 'C1', 'Fp1', 'C2', 'C4', 'C6',
       'T8', 'T10', 'TP9', 'TP7', 'CP5', 'CP3', 'CP1', 'CPz', 'CP2',
       'CP4', 'CP6', 'TP8', 'TP10', 'P9', 'P7', 'P5', 'P3', 'P1', 'Pz',
       'P2', 'P4', 'P6', 'P8', 'P10', 'PO9', 'PO7', 'PO3', 'POz', 'PO4',
       'PO8', 'PO10', 'O1', 'Oz', 'O2', 'Iz', 'I1', 'I2'], dtype=object)
```
However, this sequence does not align with the order presented in the corresponding CSV file. Additionally, there are 76 elements in this array, which conflicts with the dimensionality of the Lead Field Matrix.

Best,
Mo

**Comment by jduemose** [comment]
Hi Mo

Looking at `EEG10-10_UI_Jurak_2007.csv` it seems that the reference (Cz) has simply been moved to index zero and then Fp1 was put in Cz's original position. Why it is done like that I don't know. The channel dimension of the leadfield matrix should be one less than number of electrodes as the leadfield for each electrode has been calculated wrt. the selected reference electrode (Cz in this case). That is, the electrode names corresponding to the LF matrix is then `f["mesh_leadfield"]["leadfields"]["tdcs_leadfield"].attrs["electrode_names"][1:]`.

Best,
Jesper

**Comment by OneMore1** [comment]
Hi Jesper

Thank you for confirming the inconsistency between the LFM and the CSV file. I have also checked `EEG10-10_Neuroelectrics.csv` and found that Cz and Fp1 positions are switched there as well. I will use the sequence from `f["mesh_leadfield"]["leadfields"]["tdcs_leadfield"].attrs["electrode_names"]` in the further. Thank you again for the help.

Best,
Mo

**Comment by jduemose** [comment]
Sounds good! And thanks for the reference.

I will close this issue as resolved.
