### ISSUE TITLE
type error with newer numpy versions during headmeshing

### ISSUE THREAD

**Issue by 0nu** [simnibs/simnibs#26]
numpy >= 1.18.2 (?) linspace() throws `TypeError: 'float' object cannot be interpreted as an integer` for np.linspace(int, int, float)

in `def make_splits(mesh, testpoints, nsplits="auto"):`

    split_min = np.floor(np.max([mesh[:,2].min(), testpoints[:,2].min()]))
    split_max = np.ceil( np.min([mesh[:,2].max(), testpoints[:,2].max()]))

    if nsplits == "auto":
        nsplits = split_max-split_min+1   # <- int cast missing here
    else:
        assert isinstance(nsplits,int)
        assert nsplits > 0

    splits = np.linspace(split_min, split_max, nsplits)  # <- exception thrown here, nsplits is float
https://github.com/simnibs/simnibs/blob/065d5bd9eee1eaddc54e98029e3818bf008e1496/simnibs/msh/hmutils.py#L1765

**Comment by guilhermebs** [comment]
Hi Ole,

9046c49 should fix it. Could you please try again?

**Comment by 0nu** [comment]
Hi Guilherme,

looks good to me.
