### ISSUE TITLE
fnamecoil is not saved via opt.struct.TMSoptimize.sim_struct2mat()

### ISSUE THREAD

**Issue by 0nu** [simnibs/simnibs#27]
I think a 
`mat['fnamecoil'] = remove_None(self.fnamecoil)`

is missing here:

https://github.com/simnibs/simnibs/blob/9046c495f58ced871a28cd027966ee4a2046fb68/simnibs/optimization/opt_struct.py#L207

Reading of the coil name information already is implemented in read_mat_struct():
https://github.com/simnibs/simnibs/blob/9046c495f58ced871a28cd027966ee4a2046fb68/simnibs/optimization/opt_struct.py#L245

**Comment by guilhermebs** [comment]
Thanks! Should be fixed by 46778713dfad153954a5c38712e3dfef48a89675
