### ISSUE TITLE
Error usind dwi2cond to check ernie dataset given in simnibs

### ISSUE THREAD

**Issue by savvy73** [simnibs/simnibs#280]
I have been trying to run the ernie dataset using charm and get the anisotropy of the data using dwi2cond as given in the following page -https://simnibs.github.io/simnibs/build/html/documentation/command_line/dwi2cond.html. When running dwi2cond -check ernie, I am getting an error as follows - ERROR: No option given. Consider to rerun with option --prepro
and when I run using prepro I get the following

using preprocessed DTI tensor (ignoring other preprocessing options) ...
 
==============================
==> dwi2cond started  Wed Jan 24 11:12:40 CET 2024 ...
==============================
 
==============================
==> --prepro: Preprocessing DWI data ...
==============================
Copying DTI tensor
ERROR: Input file '--prepro' doesn't exist.
 how can I correct this?

**Comment by TorgeW** [comment]
Please provide the full command you are using.

If you are using `dwi2cond -check ...` be told that it should be `dwi2cond --check ...`

**Comment by savvy73** [comment]
once I get the anisotropy file from dwi2cond, How can I access the anisotropy matrix from DTI_coregT1_tensor.nii.gz ?
