### ISSUE TITLE
Simnibs installation in linux

### ISSUE THREAD

**Issue by savvy73** [simnibs/simnibs#283]
Hi, I was trying to install simnibs in my linux. When trying to in
![Screenshot from 2024-02-02 16-00-25](https://github.com/simnibs/simnibs/assets/154327664/c2f9fb01-3072-4780-a2ed-d9a2ab82f493)
![Screenshot from 2024-02-02 16-00-32](https://github.com/simnibs/simnibs/assets/154327664/eb7369a5-04ba-4dbc-a81f-9b457b719384)

**Comment by jduemose** [comment]
Hi this looks similar to #153. Perhaps you can have a look at this issue?
Best,
Jesper
