### ISSUE TITLE
Cannot find sub-folder label_prep and tissue_labeling_upsampled.nii.gz file

### ISSUE THREAD

**Issue by frankatimm** [simnibs/simnibs#309]
Hello,

I am currently trying to create a head model. On the Simnibs website (https://simnibs.github.io/simnibs/build/html/documentation/command_line/add_tissues_to_upsampled.html#add-tissues-to-upsampled-doc) in step 4 it says the following: 

_4. Make a copy of the tissue_labeling_upsampled.nii.gz (e.g., tissue_labeling_upsampled_orig.nii.gz) that is found in the sub-folder label_prep._

However, I am not able to find the sub-folder label_prep or the tissue_labeling_upsampled.nii.gz file in the m2m-folder of the “Ernie” example data set. Attached you can find the subfolders available in my m2m-folder. Does anyone know how to solve this problem? Thank you in advance!

Best wishes,
Franka

![image](https://github.com/simnibs/simnibs/assets/83537293/f967038b-daeb-4ac1-ac52-474d430a7c02)

**Comment by oulap** [comment]
Looks like we didn't include that folder in the example data. If you run charm again on the example data set:

`charm ernie_full org/ernie_T1.nii.gz org/ernie_T2.nii.gz`

you should get the full output

**Comment by frankatimm** [comment]
Thank you for the fast reply. 

Where am I supposed to find the full output? Because after running the command in my command line I still don't have a subfolder label_prep.

**Comment by oulap** [comment]
That command should take a while to finish. Is it still running, or did you encounter an error?

**Comment by frankatimm** [comment]
Yes, I ran the command and encountered an error. Then I closed the terminal and ran the command again and this is what I encountered: 

![image](https://github.com/simnibs/simnibs/assets/83537293/743b77c8-7ec1-4e09-89d3-54c4b7cd1c19)

**Comment by oulap** [comment]
Okay, it seems the folder m2m_ernie_full already exists. Try running the command like this:

`charm ernie_full org/ernie_T1.nii.gz org/ernie_T2.nii.gz --forcerun`

Also please note that here I'm expecting that you are doing the charm call from inside the example data folder where the folder called "org" exists.

**Comment by frankatimm** [comment]
Ok, it worked and finally finished after 5 hours of running. Thank you so much for your help!

**Comment by frankatimm** [comment]
Hi, it's me again. I tried to run step 5 now (running the command: add_tissues_to_upsampled -i simnibs.nii.gz -t ./label_prep/tissue_labeling_upsampled.nii.gz -o ./label_prep/tissue_labeling_upsampled.nii.gz --offset 50). If I do so, it shows me the following error:

![image](https://github.com/simnibs/simnibs/assets/83537293/be3abbad-2e36-49ac-90b7-f06c3fccdc37)

What should I do now? Thank you in advance for your help.
