### ISSUE TITLE
Output stiffness matrix

### ISSUE THREAD

**Issue by giadadamiani** [simnibs/simnibs#31]
Hi there! Is it possible to access the stiffness (or FEM) matrix of a SimNIBS simulation? 
Thanks for your time!

**Comment by guilhermebs** [comment]
Hello,

Sure, the stiffness is calculated when a [FEMSystem](https://github.com/simnibs/simnibs/blob/46778713dfad153954a5c38712e3dfef48a89675/simnibs/simulation/fem.py#L439) instance is created. You just need to give it a mesh and a conductivity field. The stiffness matrix is stored in the ("A" property)
