### ISSUE TITLE
Defining ROI in Uncertainty Quantification Using Matlab

### ISSUE THREAD

**Issue by nwalsh461** [simnibs/simnibs#32]
Hi SimNIBS Developers,

Thank you very much for this tool! It has been incredibly useful and very enjoyable to work with. I have a few quick questions regarding the Uncertainty Quantification.

On the tutorial of the UQ page, under Output Files, it is mentioned that mesh_roi is the mesh cropped to the roi:

https://simnibs.github.io/simnibs/build/html/tutorial/advanced/uq.html?highlight=roi

However in the Uncertainty Quantification matlab script there isn't any mention of defining the roi. What is the roi by default and is it possible to change this in the matlab script, similar to how the roi is definied in the optimization tool?

Also I was wondering if you had a reference for how the atlas used to define roi relates to the different areas of the brain? For example, if I wanted to define the roi as the DLFPC, what would the equivalent region name be in the atlas used in SimNIBS?

Kind regards,
Nick

**Comment by guilhermebs** [comment]
Hello,

Thanks for using SimNIBs!

UQ is somewhat of an experimental feature, and we do not expose all the options in the MATLAB interface, so you can't change the ROI (tissues) from the default [2], which corresponds to gray matter volume. However, what we define as ROI (tissues) in the UQ code is different from, for example the the [roi_analysis_surf.m](https://github.com/simnibs/simnibs/blob/master/simnibs/examples/analysis/roi_analysis_surf.m) example. In UQ, you can only set tissue numbers (1 for WM, 2 for GM, 3 for CSF, 4 for Skull and 4 for Skin) as "roi" (tissues), and not specific brain regions, as in [roi_analysis_surf.m](https://github.com/simnibs/simnibs/blob/master/simnibs/examples/analysis/roi_analysis_surf.m). However, if you want to have the mean expected electric field (mean of the mean) in a given brain region, you can try:

1. Run the UQ
2. Interpolate results to the middle cortical surface using [msh2cortex](https://simnibs.github.io/simnibs/build/html/documentation/command_line/msh2cortex.html)
3. Adapt [roi_analysis_surf.m](https://github.com/simnibs/simnibs/blob/master/simnibs/examples/analysis/roi_analysis_surf.m) to calculate the mean of the electric field in your ROI. However, beware that this will not give you the standard deviation or Sobol indices of the mean field in the ROI, as those are non-linear quantities.

I have never tried all the steps above together.
