### ISSUE TITLE
Mesh oversized in some direction compare to the input MRI 

### ISSUE THREAD

**Issue by tmedani** [simnibs/simnibs#35]
Hello, 

I found a strange behavior, where the output mesh does not overlay correctly on the MRI in one direction. 

Here are some views of the results

from this angle, the mesh is correct, correctly fits the MRI,

![image](https://user-images.githubusercontent.com/37831900/91266784-cbab5c00-e726-11ea-8622-499b4dea54d8.png)

However, from this angle, it's bigger
![image](https://user-images.githubusercontent.com/37831900/91266679-9737a000-e726-11ea-84a7-23712942671a.png)

Before going for further investigation, I would like to know if you have already faced to this problem before?

I'm not sure, but I think it's related somewhere to the coordinates system conversion / and the different voxel resolution!

Any other points to investigate?

Thanks for your help. 

Best,

**Comment by oulap** [comment]
Hi,

Haven't seen that before. I presume this is a standard headreco run?

Can you check if the <subid>_masks_contr.nii.gz and <subid>_final_contr.nii.gz files match the input mri.

**Comment by tmedani** [comment]
Hi, 

here is the view with the volume  '*_final_contr.nii.gz 
![image](https://user-images.githubusercontent.com/37831900/91326860-ad228080-e779-11ea-9500-7a38791c347b.png)
![image](https://user-images.githubusercontent.com/37831900/91326930-c3304100-e779-11ea-81c9-ac36248a9e5a.png)

It fits in all direction, 

I have deleted the *_masks_contr.nii.gz, 

I will re-run headreco and check again some other points, and I will let you know.

 Thanks for your answer.

Best,

**Comment by tmedani** [comment]
Hello, 

After investigations, we found that the problem is at our software level, everything is correct from headreco.

Thanks for your help.

Best
