### ISSUE TITLE
Compact and spongy bone conductivities 

### ISSUE THREAD

**Issue by giadadamiani** [simnibs/simnibs#38]
Hi there! In the standard_cond.m script, we can change conductivity values for compact and spongy bone, but I was wondering whether this skull segmentation was included in the current version of SimNIBS, since changing these values does not affect the results of the simulation. 
Thanks for your help!

**Comment by oulap** [comment]
Hi,

Currently the head models we generate only have a single bone compartment (with label 4), and so the conductivity is also controlled for the entire bone tissue. That's the reason why changing the compact and spongy bone conductivities does not change the simulation results. We are working towards including more detailed head models with both spongy and compact bone segmented separately.

Best,
Oula

**Comment by giadadamiani** [comment]
Thank you for your answer! 
Best wishes,
Giada
