### ISSUE TITLE
Mesh and fill the air cavities/holes in the head model

### ISSUE THREAD

**Issue by tmedani** [simnibs/simnibs#39]
Hi,

We would like to know if it's possible to mesh the air cavities of the skull with headreco?

![image](https://user-images.githubusercontent.com/37831900/95634789-8d9c9a00-0a3f-11eb-9fc7-c7972a3687b4.png)
 
![image](https://user-images.githubusercontent.com/37831900/95634832-aa38d200-0a3f-11eb-82e5-fcd212d5dc2b.png)

Thank you in advance
Best

**Comment by oulap** [comment]
Hi,

The cavities are actually removed in the last step of headreco. It's possible to skip the step, but there's no flag for doing it at the moment. Do you want to do it for all subjects, or just some? We could add the flag if you need this functionality.

**Comment by tmedani** [comment]
Hi @oulap,

Thanks for your answer, 

Currently, we don't want to have any cavities or any holes in the mesh for all users (and all subjects), 

Our local solution (temporary) is either to mesh the air and assigned it with very low conductivity or just merge these holes with a skull, but for both methods, we need to re-mesh the output of headreco. 

> We could add the flag if you need this functionality.

yes please, it will be great if you can add a flag that can include the mesh of the cavities with headreco. 

Thanks in advance.
Best

**Comment by oulap** [comment]
This took a while, but the new SimNIBS version now has a --keep_air flag. If you pass the flag when calling headreco, the resulting meshes include the air in the cavities and throat.

**Comment by tmedani** [comment]
> This took a while, but the new SimNIBS version now has a --keep_air flag. If you pass the flag when calling headreco, the resulting meshes include the air in the cavities and throat.

Thank you this is awesome,
I will update the code check it at our end

**Comment by StevenBm** [comment]
Hi, 

This is great work and the segmentation works great. I did a head segmentation with this keep_air flag, which adds the air in the cavities and the throat. This, however, makes the simulations non-functioning due to non-defined conductivities for materials 10 and 11. I assumed both were air and added very low (nonzero for stability) conductivities in cond.py at positions 10 and 11 in the conductivity array, which made the simulations function again. 

Is this assumption for the materials correct?

**Comment by oulap** [comment]
Previously the cavities were just assigned to background air (and removed from the mesh) so they were basically non-conducting. This is a bit of a specialty flag, so I didn't edit cond.py, but yeah just add a small value there and you should be fine.

**Comment by StevenBm** [comment]
@oulap Thanks for the quick reply!
