### ISSUE TITLE
TMS simulation big difference between using .nii.gz and .ccd for coil description

### ISSUE THREAD

**Issue by vfonov** [simnibs/simnibs#4]
I stumbled upon a  big differences in simulation results, when coil descriptions is changed from .nii.gz file to .ccd file, when running simnibs in script mode. 
See attached files : simulation.py - script for simulation using ernie dataset , with coil description in .nii.gz format , simulation_ccd.py - same script, but with coil description in .ccd format. 
The normE for the second position show a big discrepancy in location see gmsh_2nd_electrode_nii_coil.png and gmsh_2nd_electrode_ccd_coil.png:

nii: <img width="1525" alt="gmsh_2nd_electrode_nii_coil" src="https://user-images.githubusercontent.com/628822/61559432-ad5d3200-aa37-11e9-8dec-f7b10f415a6d.png">

ccd:<img width="1525" alt="gmsh_2nd_electrode_ccd_coil" src="https://user-images.githubusercontent.com/628822/61559446-b3eba980-aa37-11e9-95eb-89adde816d73.png">

simulation.py
```
import os
import shutil
from simnibs import sim_struct, run_simnibs
s = sim_struct.SESSION()
s.fnamehead = '/Users/vlad/TMS/examples/simnibs_examples/ernie/ernie.msh'
s.pathfem = '/Users/vlad/TMS/simulations//temp'

s.fields = 'e'
s.open_in_gmsh=False
s.map_to_vol=True
tms_list = s.add_tmslist()
tms_list.fnamecoil = '/Users/vlad/src/simnibs/simnibs/ccd-files/Magstim_70mm_Fig8.nii.gz'
pos = tms_list.add_position()
pos.matsimnibs = [[-0.559749, 0.000000, 0.828662, 66.260584],
[0.374745, -0.891902, 0.253134, 17.962578],
[0.739086, 0.452229, 0.499241, 70.441510],
[0.000000, 0.000000, 0.000000, 1.000000]]
pos.didt=10000000.000000
pos = tms_list.add_position()
pos.matsimnibs = [[-0.601914, 0.000000, -0.798561, -56.045290],
[-0.352622, -0.897226, 0.265788, 25.679434],
[-0.716490, 0.441572, 0.540052, 82.929580],
[0.000000, 0.000000, 0.000000, 1.000000]]
pos.didt=10000000.000000

```

simulation_ccd.py
```
import os
import shutil
from simnibs import sim_struct, run_simnibs
s = sim_struct.SESSION()
s.fnamehead = '/Users/vlad/TMS/examples/simnibs_examples/ernie/ernie.msh'
s.pathfem = '/Users/vlad/TMS/simulations//temp_ccd'

s.fields = 'e'
s.open_in_gmsh=False
s.map_to_vol=True
tms_list = s.add_tmslist()
tms_list.fnamecoil = '/Users/vlad/src/simnibs/simnibs/ccd-files/Magstim_70mm_Fig8.ccd'
pos = tms_list.add_position()
pos.matsimnibs = [[-0.559749, 0.000000, 0.828662, 66.260584],
[0.374745, -0.891902, 0.253134, 17.962578],
[0.739086, 0.452229, 0.499241, 70.441510],
[0.000000, 0.000000, 0.000000, 1.000000]]
pos.didt=10000000.000000
pos = tms_list.add_position()
pos.matsimnibs = [[-0.601914, 0.000000, -0.798561, -56.045290],
[-0.352622, -0.897226, 0.265788, 25.679434],
[-0.716490, 0.441572, 0.540052, 82.929580],
[0.000000, 0.000000, 0.000000, 1.000000]]
pos.didt=10000000.000000

```

**Comment by guilhermebs** [comment]
Hi Vladimir,

Looks like the coil z axis "flipped". That is, the coil is pointing away from the head. If you just flip the "z" axis in both of them, you should get very similar fields

example:
```
pos.matsimnibs = [[-0.559749, 0.000000, -0.828662, 66.260584],
[0.374745, -0.891902, -0.253134, 17.962578],
[0.739086, 0.452229, -0.499241, 70.441510],
[0.000000, 0.000000, 0.000000, 1.000000]]

```
This happens because in the nifti files, we only define the coil dA/dt for positive "z" values, and assign a value of zero elsewhere while in the CCD we calculate it on the fly. [Please see here for how coil coordinates and directions are defined in SimNIBS](https://github.com/simnibs/simnibs/blob/master/docs/data/coil_axesorientation.pdf)

**Comment by vfonov** [comment]
I see, thank you for the clarification.

**Comment by vfonov** [comment]
by the way, documentation on this doesn't render properly in safari
<img width="750" alt="Screen Shot 2019-07-22 at 10 01 56" src="https://user-images.githubusercontent.com/628822/61638660-dd8b1780-ac67-11e9-8211-606e5d213f75.png">

**Comment by guilhermebs** [comment]
Thanks for the heads up, should be fixed now
