### ISSUE TITLE
headreco: Uneven surface leads to weird TMS coil positions

### ISSUE THREAD

**Issue by 0nu** [simnibs/simnibs#42]
Hey there,

while the headreco pipeline works very well for us in general, we (@konstantinweise) run into problems with the tissue surfaces not being smoothed.   
![headreco_vs_mri2mesh](https://user-images.githubusercontent.com/3918989/97164259-27737f00-1782-11eb-99c0-4c022db4487f.jpeg)
left: headreco, right: mri2mesh

I guess this isn't a big deal if you want to get E-fields for given TMS coil position from a lab session, but this becomes a bigger problem when doing TMS coil optimizations because the coil z orientation is set orthogonal to the skin surface. Also, meshes with higher resolution lead to even stronger coil deviations.

Here is an example of a set of possible coil positions for the optimization procedure ([optimize_tms.get_opt_grid()](https://github.com/simnibs/simnibs/blob/f634891ec496653f3959edf90f1e18291c410dea/simnibs/optimization/optimize_tms.py#L75)).  You can clearly see that the coil orientation is not what one would expect. I implemented some laplacian filtering to try to smooth the skin surface before the grid creation in [optimize_tms._create_grid()](https://github.com/simnibs/simnibs/blob/f634891ec496653f3959edf90f1e18291c410dea/simnibs/optimization/optimize_tms.py#L11) -- this seems to fix the issue with the need for a new import ([trimesh](https://trimsh.org/trimesh.smoothing.html)).

Top: `headreco -v 1`; bottom: `headreco -v 2`
left: laplacian smoothing; right: original data.
![smooth_com](https://user-images.githubusercontent.com/3918989/97164515-8933e900-1782-11eb-9921-e85b519d9eb9.png)

What do you think? This could also be implemented during / after the meshing procedure.  

Some code to be inserted possibly here https://github.com/simnibs/simnibs/blob/f634891ec496653f3959edf90f1e18291c410dea/simnibs/optimization/optimize_tms.py#L15

```python
    if smooth != 0: # this is the smoothing factor in the plot above
        import trimesh
        tri_node_nr = msh_skin.elm.node_number_list[msh_skin.elm.triangles-1] -1
        tri_node_nr = tri_node_nr[:,:3]
        a = msh_skin.nodes.node_coord[tri_node_nr]
        a.shape
        tri_msh = trimesh.Trimesh(vertices=msh_skin.nodes.node_coord,
                                  faces=tri_node_nr) # create a Trimesh object based on the skin tris
        smooth_mesh = trimesh.smoothing.filter_laplacian(tri_msh, lamb=smooth) # do smoothing
        msh_skin.nodes.node_coord = smooth_mesh.vertices # overwrite simnibs Mesh object's nodes
        msh_skin.elm.node_number_list[:,:3] = np.array(smooth_mesh.faces)+1 # ... and vertices assignments
```

**Comment by oulap** [comment]
Hi,

You should be able to smooth the triangle normal already see line 41:
`normals_roi = msh_roi.triangle_normals(smooth=1)`

Have you tried increasing the smoothing steps there?

**Comment by ZsoltTuri** [comment]
Hi,

I encountered the same issue with headreco() as described above, in addition some of the head meshes have extra spikes especially around the eyes and the face area. 

@oulap: Is it possible to smooth the skin surface already when calling headreco()?
In "...SimNIBS-3.2.1\simnibs_env\Lib\site-packages\simnibs\msh" I found the hmutils.py file and and the make_surface_mesh() function, where there is a parameter called n_smooth. This is set to value 1 initially. Is this what needs to be changed?
Interestingly, in the headreco report log file I found the following info: "Smoothing 5 time(s)". 

What is your suggestion?

**Comment by oulap** [comment]
Hi,

@ZsoltTuri the smoothing call is actually done from headreco.py where the default argument (nsmooth=1) is overriden with 5.
The exact line in headreco.py is 1543

` off[key] = hmu.make_surface_mesh(mod[key], off[key], 1, 1, vertex_density, 5)[0]`

You can try to change the 5 to 10 or even 20 to see if that works better. Please report back if you try it, we're definitely open to changing the number in the next version, making it a parameter, or swithching back to Laplacian smoothing for the skin if that works better.

**Comment by ZsoltTuri** [comment]
Hi,

@oulap here is my interim feedback: I followed your instructions and tried 10, 15 and 20 repetitions. The simulation with 20 repetitions seemed to smooth the head surface pretty well. I will re-run the smoothing on the entire group and then send you my feedback.

**Comment by oulap** [comment]
Hi,

Thanks for the update @ZsoltTuri ! Let us know how it goes for the rest of the subjects.

**Comment by ZsoltTuri** [comment]
Hi,

@oulap this is just a follow up that the smooth parameter at value 20 seems to smooth nicely the skin compartment in my studied sample. Again, thank you for the help.

**Comment by 0nu** [comment]
Hey there, 
a quick update: 
I also tried the skin-smoothing during the meshing process via ` off[key] = hmu.make_surface_mesh(mod[key], off[key], 1, 1, vertex_density, XX)[0]` with `40` (left), `20` (middle), and standard `5` (right) for a headreaco `density=2.0` mesh, see below.
![40_20_5](https://user-images.githubusercontent.com/3918989/100141199-53257a00-2e92-11eb-958c-da0c02d03238.png)

20 smoothing steps lead to a better result, but you can still see the slices (1mm).

I'll try your initial idea soon and get back to you.

**Comment by oulap** [comment]
@ZsoltTuri & @0nu 

Thanks for the feedback! We will increase the smoothing steps in the next release. 

@0nu If you want the skin as smooth as in mri2mesh then you should probably switch back to Laplacian smoothing.

**Comment by 0nu** [comment]
> Hi,
> 
> You should be able to smooth the triangle normal already see line 41:
> `normals_roi = msh_roi.triangle_normals(smooth=1)`
> 
> Have you tried increasing the smoothing steps there?

This works pretty well, thanks! For high-density meshes 50-100 smoothing steps led to a very smooth coil orientation distribution.
