### ISSUE TITLE
Issue with mni2subject_coords and optimisation

### ISSUE THREAD

**Issue by giadadamiani** [simnibs/simnibs#45]
Dear SimNIBS team,

The ROI in our simulations is defined with the MNI coordinates (-35.50, 49.40, 32.40) of the cortical projection of the 10-20 EEG point F3 (from [Okamoto 2004](https://pubmed.ncbi.nlm.nih.gov/14741647/)). I checked that these were on the cortical surface of the MNI head provided in your example dataset. However, when using the function mni2subject_coords with the ernie head mesh, the new coordinates (-35.97 49.54 66.39) are not on the cortical surface of the ernie mesh, as you can see in the figure below.
![mni2subj_coords_ernie](https://user-images.githubusercontent.com/57667428/101017542-80e18180-356a-11eb-9fd6-bba40a40dc12.png)

Before realising that the new coordinates were not in the GM, we have used them for the optimisation of a multielectrode array using the script 'tdcs_optimize_mni.m'.  

Now, I have two questions:
1. Is there a way to ensure that the mni2subject_coords function outputs coordinates on the same tissue as the tissue that contained the input MNI coordinates?
2. Does the optimisation tool project the ROI coordinates inserted by the user to the closest point on the cortex or does it optimise the field in a tissue different than the GM if the coordinates of the ROI are not in the GM? I'd like to understand if the optimisation tool optimised the field using the ROI projected onto the GM or the ROI in the CSF/skull.  

Thanks for your time!

Giada

**Comment by oulap** [comment]
Hi Giada,

1. The point correspondences between the MNI space and the subject space are limited by the non-linear transform, and it's not straight-forward to ensure that a point that is in gray matter in the MNI volume space would be in gray matter in subject volume space. This would require projecting onto the gray matter surface, which brings me to point 2.

2. The optimization code does project the point onto the target tissue. So the optimization should be done using the correct tissue type.

Best,
Oula

**Comment by giadadamiani** [comment]
Hi Oula,

Thanks for your answer, it is very helpful!   
Would it be possible to access the code to project the point onto the gray matter, so that we can use the same ROI coordinates in both the optimisation of the tDCS montage and in the results analysis?  

Thanks again for your time!
Giada

**Comment by oulap** [comment]
I think the summary should print the index of the target, which corresponds to an index in the mesh. 
You could then use that to find the coordinate.

**Comment by giadadamiani** [comment]
Unfortunately there is no target index in the summary of our optimisation... 
However, we have projected the point with our own code, which should be very close to the coordinates used in the optimisation.

Thank you very much for all your help!

Giada
