### ISSUE TITLE
Pancake Brain issue with simnibs

### ISSUE THREAD

**Issue by enemonsieur** [simnibs/simnibs#471]
![image](https://github.com/user-attachments/assets/5dbcf6ec-2fc5-4d47-bb5a-955b76ebdbb8)

I've been struggling with modelling some brain tissues. It seems like it only creating a mesh of the surface, and the other part of the brain don't seem to work.
I used charm, changed the setting.nii from "atlas" to "mni". And ran the run_simnibs(S). I also added a stroke lesion using the command of simnibs.

Did anyone encouter that sort of issue? Or should I add more details?

Best!

**Comment by enemonsieur** [comment]
Hi,
I'm writing again in case any one knows about that issue or if I should add more details?

**Comment by TorgeW** [comment]
https://github.com/simnibs/simnibs/discussions/476
