### ISSUE TITLE
NormalE result in tES simulation from GUI

### ISSUE THREAD

**Issue by SaraRomanella** [simnibs/simnibs#49]
Hi all, 
I have a doubt about tDCS simulation over the GUI. While using an anode and cathode, the resulting electric field I get is always with positive values. I know we are only looking at strength in the case of the NormE result and that we can see the direction of the field in E, but I cannot seem to find a resulting representation of the NormalE.
For example, I would need negative values under the cathode and positive ones under the anode, as we can usually see when we have a graphic representation of the e-field in NormalE.
Am I missing something? Can I compute NormalE from GUI? Or from script maybe?
Thanking you in advance.

**Comment by SaraRomanella** [comment]
Sorry, just figured it out!

**Comment by ParlikarR** [comment]
Hi Sara,
I recently introduced myself to this software and encountered the same observation as you did as far as the anode and cathode electric fields are concerned. I saw your old post and also that you figured it out. Would you be kind enough to help me understand this?
Thanks,
Rujuta
