### ISSUE TITLE
Stimulation electrode within the volume conductor. 

### ISSUE THREAD

**Issue by tmedani** [simnibs/simnibs#50]
Dear SimNibs team, 

I'm wondering if it's possible to simulate TES with electrodes placed not on the scalp but under the skin. 

Is this something doable with SimNibs? 

Thank you in advance for your reply. 

Best regards

**Comment by oulap** [comment]
It is possible but requires quite a bit of extra work and scripting. 

So the short answer is: it's not supported at the moment.

In case you really want to do it, we can probably provide some example code, but it will take some time to get it up and running.

**Comment by tmedani** [comment]
Hi @oulap 

Thanks for your answer, indeed in theory this is doable, it may require some change on the boundaries conditions.   

> In case you really want to do it, we can probably provide some example code, but it will take some time to get it up and running.

your code is Matlab or python based? 

I can indeed give it a try and work on it in my free time, 
so it can be great if you can share a script example.

Thanks in advance.
