### ISSUE TITLE
Reuse HCP structural pipeline output

### ISSUE THREAD

**Issue by mlueckel** [simnibs/simnibs#51]
Hi,

is it possible to (re)use the output from the HCP structural pipeline instead of running the FSL and Freesurfer procedures all over again?

Thanks for your help, 
Max

**Comment by oulap** [comment]
Hi Max,

Unfortunately the HCP pipeline only handles the brain and does not segment extracerebral structures. Because of this, it's not straight-forward to feed in previous FS and FSL runs into mri2mesh.

Best,
Oula

**Comment by mlueckel** [comment]
Hi Oula,

alright, thanks for your answer! I will try to find another solution then.

Best,
Max
