### ISSUE TITLE
gmsh within simnibs uses system libstdc++ instead of simnibs lib

### ISSUE THREAD

**Issue by Craskermasker** [simnibs/simnibs#53]
I'm running headreco and simnibs (latest version 3.2.3, installed using conda) within a cluster computing environment (CentOS Linux release 7.9.2009 (Core)). Ran into a weird bug where headreco consistently errors at the stage where it calls the Gmsh packaged within simnibs. I can reproduce the error by running that Gmsh directly, which gives the following error.

```
/home/fs0/<user>/.conda/envs/simnibs_env/lib/python3.7/site-packages/simnibs/bin/linux/gmsh: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/fs0/<user>/.conda/envs/simnibs_env/lib/python3.7/site-packages/simnibs/bin/linux/gmsh)                                                                                                                                          
/home/fs0/<user>/.conda/envs/simnibs_env/lib/python3.7/site-packages/simnibs/bin/linux/gmsh: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/fs0/<user>/.conda/envs/simnibs_env/lib/python3.7/site-packages/simnibs/bin/linux/gmsh)                                                                                                                                       
/home/fs0/<user>/.conda/envs/simnibs_env/lib/python3.7/site-packages/simnibs/bin/linux/gmsh: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/fs0/<user>/.conda/envs/simnibs_env/lib/python3.7/site-packages/simnibs/bin/linux/gmsh)                            
```                                                                                                            

I think Gmsh is inappropriately using the systemwide /lib64 which has an old version of this library, rather than using the one distributed within the conda environment at either of these two locations:

```
$CONDA_PREFIX/lib/python3.7/site-packages/simnibs/bin/linux
$CONDA_PREFIX/lib
```

I was able to resolve this either by manually setting my LD_LIBRARY_PATH environment variable, or configuring the simnibs_env conda environment to set it on load by using

`conda env config vars set LD_LIBRARY_PATH=$CONDA_PREFIX/lib`

I'm not sure if this is a bug, leaving it here in case anyone runs into similar issues in cluster or older linux environments.

**Comment by Craskermasker** [comment]
This is how the gmsh seems to be configured to look for libraries

```
$ objdump -p gmsh | grep RPATH 

 RPATH                $ORIGIN/../lib:/petsc-3.10.2/real_mumps_seq/lib:/usr/local/lib:/usr/local/lib64
```

I would guess that moving the file at:
`
$CONDA_PREFIX/lib/python3.7/site-packages/simnibs/bin/linux/libstdc++.so.6`

into a subdirectory named lib should be the proper fix the issue

**Comment by axthi** [comment]
Thanks for informing us! Did you install SimNIBS using the supplied installer package, or manually via downloading the wheel?

**Comment by Craskermasker** [comment]
I installed following the instructions here (using pip into a conda environment)
https://simnibs.github.io/simnibs/build/html/installation/conda.html
