### ISSUE TITLE
CHARM availability

### ISSUE THREAD

**Issue by MartinGrignard** [simnibs/simnibs#54]
Hi,

First, I'd like to thank you for your great tool!
I'm preparing a new study where I would like to use SimNIBS and the recently published CHARM pipeline.
Unfortunately, I can't seem to find any documentation on how to use it on the [charm-gems repo](https://github.com/simnibs/charm-gems).

Is there already a way to call it in a script (from a dev branch or something)?
The reason I want to use it is that I would like to run a pipeline defined with Nextflow on many subjects, thus relying on a HPC cluster. To do so, I want to containerize the tool but since Matlab is required for Headreco and not for CHARM, the latter seems a better option.

I read [here](https://neuroimage.usc.edu/brainstorm/Next) that Headreco would get removed from SimNIBS in version 4 so I suppose I'll have to wait for that version. Is that right?

Have a nice day :slightly_smiling_face:

**Comment by oulap** [comment]
Hi,

The charm-gems repo is a backend library for the segmentation module that will be included in the new version of SimNIBS. 

We're not quite ready for the release yet, but are working hard to get the new version out. 
So you have to wait a bit longer before charm is available :)

**Comment by MartinGrignard** [comment]
@oulap  thanks for the follow up, I'll keep an eye on it :slightly_smiling_face:
