### ISSUE TITLE
mesh_show_results.m function 

### ISSUE THREAD

**Issue by tmedani** [simnibs/simnibs#56]
Hello all, 

I'm trying to find the function "mesh_show_results.m" but I can't find it in the matlab package? 

In the main paper it's said that this function comes as a part of SimNIBS version 2.1.2, and provides visualizations of the output fields using MATLAB plotting tools, as well as some summary values for the field strength and focality. 

Could you please point me to its location?

Thanks in advance.

Best,
Takfarinas

**Comment by axthi** [comment]
Hi Takfarinas,
please just update to the latest SimNIBS version to fix this problem.
Best,
Axel
