### ISSUE TITLE
Current visualization within SimNibs

### ISSUE THREAD

**Issue by tmedani** [simnibs/simnibs#57]
Hello, 

I found your OHBM abstract at
 https://ww4.aievolution.com/hbm2001/index.cfm?do=abs.viewAbs&abs=2104

and I'm wondering if we can use simnibs to visualize the current as in this figure?

![image](https://user-images.githubusercontent.com/37831900/118873970-35fcc180-b89f-11eb-8eec-43d3073f6013.png)

If yes, could you point me to the functions?

Thank you.

**Comment by axthi** [comment]
This has been done in Gmsh by selecting a thin slab in which the results are visualized, and then selecting J and setting the min and max limits by hand. 
Please have a look at our tutorial for gmsh:
https://simnibs.github.io/simnibs/build/html/tutorial/visualization.html

Selecting the slab was done by using two clipping planes, one in front and one behind the slab.
