### ISSUE TITLE
parallel analysis 

### ISSUE THREAD

**Issue by alirez4v** [simnibs/simnibs#58]
Dear SIMNIBS developers,

Does SIMNIBS and specially "headreco" tool can be run parallel? I'm researching on electric field distribution for tDCS with specific electrodes size and shape, for this purpose I have to study over 50 subjects and since derivation of head model from MR images take ~3 hours I was wondering if I could run headreco parallel with high performance computational clusters.

Best regards,
Alireza.

**Comment by axthi** [comment]
Yes, you can run several headreco for the different subjects at the same time on HPC clusters.
