### ISSUE TITLE
Binary tissue probability maps

### ISSUE THREAD

**Issue by CogNewLAB** [simnibs/simnibs#6]
Hello,

I am trying to run a nifiti through headreco using matlab and I am running into an issue binarizing tissue proability maps to get the msh file
<img width="1073" alt="Screen Shot 2019-08-06 at 12 44 31 PM" src="https://user-images.githubusercontent.com/52084427/62559036-2afeab80-b848-11e9-96dd-90570ed1c2a5.png">

I have attached the screenshot

Any help would be greatly appreciated.

**Comment by guilhermebs** [comment]
Hi,

Can you please make sure that calling "matlab" in the terminal starts a matlab instance?

Best Regards,
Guilherme

**Comment by CogNewLAB** [comment]
Hi Guilherme, 

I have ensured that calling "matlab" indeed opens matlab.

I am still having the same issue unfortunately.

Any further help?

Ben

**Comment by guilhermebs** [comment]
We can't reproduce it over here.
Headreco calls matlab as part of the segmentation pipeline. My guess is that the matlab call is somehow returning before the segmentation is done. One further evidence of that is that you normally get a few lines with matlab version info at this point, and I don't see anything there. It might be that "matlab" command does not go directly to the executable or to a link to the executable, but rather to a bash file or something like it.

What do you get if you run

ls -lah \`which matlab\`

**Comment by guilhermebs** [comment]
I'm closing the issue due to inactivity
