### ISSUE TITLE
Unexpected error whith update_simnibs

### ISSUE THREAD

**Issue by tmedani** [simnibs/simnibs#60]
Dear team, 

when I tried to update the software using the cl "update_simnibs" I got this error:

![image](https://user-images.githubusercontent.com/37831900/121232947-f6464b80-c846-11eb-933d-26bcdce7e0cf.png)

Any idea how to solve it?  tor should I install it again?

Thanks 

Takfarinas

**Comment by oulap** [comment]
Just try a clean re-install, that should work. I'll check what's wrong with the update.
