### ISSUE TITLE
Confusion around files, data shapes, and vector fields (normE &  E_normal)

### ISSUE THREAD

**Issue by caglorithm** [simnibs/simnibs#61]
Dear SimNIBS team, first of all, thanks for your amazing work. I'll come straight to the point: I want to extract the normal E field components on a white-matter brain region in the aal2 atlas. I have managed to do so with `normE` but I'm interested in the normal component of the vector. 

## Extracting normE

```python
aal_atlas = nib.load("data/aal/aal2.nii.gz") # atlas in MNI space
head_mesh = simnibs.read_msh("data/ernie/simulations/gw_inphase/ernie_TDCS_1_scalar.msh")
gray_matter = head_mesh.crop_mesh(2) # extract white matter
# get the coordinates of the gray matter (is this ok?)
elm_centers = gray_matter.elements_baricenters()[:] 

# get MNI coords of area from atlas
area_number = 16 # example
area_mni_coords = np.array([np.int_(np.round(x)) for x in apply_affine(img.affine , np.argwhere(img.get_fdata()==area_number))])
# transform area coordinates to subject coordinates
area_subject_coords = simnibs.mni2subject_coords(area_mni_coords, 'data/ernie/m2m_ernie/')

# generate binary roi vector that is a mask for the specified area
r = 3. # radius
roi = np.array([True if np.any(np.linalg.norm(f - area_subject_coords, axis=1) < r) else False for f in elm_centers])

# normE
normE = gray_matter.field['normE'][roi]

# note the shape of the element coordinates:
print(gray_matter.elements_baricenters()[:].shape)
#  is the same as the shape of the field
print(orig_gray_matter.field['normE'][:].shape)
```
```python
Output: 
(980931, 3)
(980931,)
```

This works kind of ok, although it takes quite some time to compute the roi vector (specifically due to `np.linalg.norm`).

## Extracting E_normal

Now, as said above, I actually want to get the normal component of `E` on the white matter for a specific roi. For that, I chose `Interpolate to cortical surface` in the GUI which produces outputs in the folder `subject_overlays/`. I try to apply the same logic as above:

```python
head_mesh = simnibs.read_msh("data/ernie/simulations/gw_inphase/subject_overlays/ernie_TDCS_1_scalar_central.msh")
# this time I can't crop this  object, because it apparently contains only the cortex (which is fine)
gray_matter = head_mesh
# I get the coordinates 
elm_centers = gray_matter.elements_baricenters()[:]

# to see if I can do the same as above, I check the shapes of these objects
print(gray_matter.elements_baricenters()[:].shape)
print(gray_matter.field['E_normal'][:].shape)
print(gray_matter.field['E_norm'][:].shape)
```
However, this time, I get a different output:
```python
Output: 
(535702, 3)
(267855,)
(267855,)
```

I have a few questions regarding this:
* Is my above approach to extract the field per AAL2 ROI ok?
* Why does the  first and the second method give me vastly different number of baricenters (980931 vs 535702)? Both should contain only the white matter, correct?
* Why is the number of field elements and the number of baricenters different in the second method? (535702 vs 267855, which is almost half, but not quite)?
* It seems like the output in `subject_overlays/` is in MNI space, although I haven't enabled that option. Is this the case?

I'd really appreciate any help on this! Thanks!

**Comment by oulap** [comment]
Hi,
I think the way you get the AAL2 ROI is okay. The reason for the different number of elements is that in the first case you're getting the elements, i.e. tetrahedra, in the second case the elements are the triangles (of the GM surface), and finally the data lives on the nodes of that surface. 

The surfaces in subject_overlays are in subject space, not MNI, the MNI results would appear in a separate folder if that option was ticked.

As you're interested in the normal component as well, I suggest doing the full analysis using the central GM surface, i.e., also the first part where you're analysing the norm. To get the roi in the right place, you can use the surface atlases defined on fsaverage. BTW you're talking about white matter, but in the code everything seems to be done on gray matter, was that just a mix-up?
