### ISSUE TITLE
TMS optimization

### ISSUE THREAD

**Issue by Tanush99** [simnibs/simnibs#62]
Hello SimNIBS team,

Thanks for the amazing product! Currently however, whenever I seem to run TMS optimizations to find optimal coil positions, the end result is a affine transformation matrix. An example, of one result I got was :

([[-5.79115569e-02, -9.97390307e-01, -4.31141172e-02, -6.98038668e+00],
                           [-5.97163587e-01,  3.65657237e-17,  8.02119474e-01, -9.03495216e+01],
                           [-8.00026189e-01,  7.21981685e-02, -5.95605173e-01,  3.71688136e+01],
                           [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

What exactly does this affine transformation matrix mean? Is this affine used to calculate the optimal coil position by also using the center position? If not, how is it possible to interpret this matrix?

Thanks

**Comment by fangcao** [comment]
Thanks! 

The last column of the affine matrix gives the position of the coil center. If you open a T1 image with a visualization tool, like freeview, and you set the RAS coordinate to be [-6.98, -9.03, 3.72] (the same as your example), then the position of your cursor is the coil center. Columns 1-3 define the direction of the coil, corresponding to coordinates X, Y, and Z, which are marked as 'SimNIBS' in the following image:
![image](https://user-images.githubusercontent.com/6490752/122905641-afca1400-d351-11eb-8aa2-657f7c5e5bd4.png)

**Comment by Tanush99** [comment]
Hello @fangcao! Thank you so much for your answer. I've been searching for days for the answer to this conundrum and I've been able to start my research due to this response. Just as a small follow-up question, since you mention that columns 1-3 of an affine matrix represent the direction of the coil, what do the numbers exactly mean? For example, since the first column corresponds to the  X coordinate, why are there 3 values in the first column? Which value corresponds to the X coordinate? Do the average of the 3 values in the first column correspond to the value of the X coordinate? I am asking since in the simnibs graphical user interface(GUI), there is only one X coordinate:

![simnibs question](https://user-images.githubusercontent.com/63757371/125033093-ba6bf500-e043-11eb-9e45-f5e878c49fd1.JPG)

So why are there 3 values in the columns 1-3 of an affine matrix corresponding to the X, Y and Z coordinates? Shouldn't there only be 1 value?

Thank you in advance

**Comment by fangcao** [comment]
Hello!

It is good to hear that you made progress. I think you were confused with the concepts of coordinates system and coordinates transformation. If you use 3D imaging modalities, you need 3 values to uniquely determine a position of a point, that are the X, Y, Z in Simnibs GUI, in the RAS coordinate system. And the coil coordinate system I showed you in my last message is another coordinate system. If you want to transform from the coil coordiante system to the RAS coordinate system or vice versa, you need to use affine transformation. The representation of affine transformation is a 4x4 matrix. You can google the definition, and there are many good explanations.
 
Good luck.

**Comment by Tanush99** [comment]
Hello @fangcao! Thanks for the answer. Really appreciate it. Just as a follow-up question, I was wondering what the coil coordinate system was which you were talking about in your last comment. Are they just voxel coordinates? I'm just asking since it isn't entirely clear to me why there are 3 values for the X coordinate, 3 for they Y coordinate and 3 for the Z coordinate. 

For example, when I take the 3 values corresponding to the X coordinates in the matrix that was outputted using TMS optimization:
([[-5.79115569e-02, -9.97390307e-01, -4.31141172e-02, -6.98038668e+00],
[-5.97163587e-01, 3.65657237e-17, 8.02119474e-01, -9.03495216e+01],
[-8.00026189e-01, 7.21981685e-02, -5.95605173e-01, 3.71688136e+01],
[ 0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

The values are -5.79115569, -5.97163587 and -8.00026189 for the X coordinates since they are in column 1. When I apply affine transformation using the affine matrix of the T1fs_conform.nii file that was generated in the headreco process of the head mesh that I am doing the TMS optimization on, I am getting 3 values. For this example, when I do affine transformation on -5.79115569, -5.97163587 and -8.00026189, I am getting the values: -96.975, 131.342, -91.373. These 3 values are all corresponding to the X coordinate since they are derived from doing the affine transformation from the values in column 1 in the matrix above. Why are there 3 values corresponding to the X coordinate even after doing this transformation. Do I need to do one more step to turn these 3 values into a single value corresponding to the X coordinate since there is only one RAS corresponding to the X coordinate as shown below:
![image](https://user-images.githubusercontent.com/63757371/125896541-e4c03713-754a-472f-b0d5-e2485e3f893d.png)


A second final question I had was comparing between RAS coordinates. I understand that although RAS coordinates are coordinates from the patient's perspective, they can vary per MRI scan. For example, the subthalamic nucleus may be at RAS coordinates of [7.63, 9.78. 11.21] in one MRI scan but a different RAS coordinate such as [8.92, 21.23, 5.11] in another MRI scan. Is there some sort of a central coordinate system where same structures have the same coordinate(for example, using the example above, the subthalamic nuclei of both MRIs would have the same coordinates) so that coordinates can be compared directly? This is because I will be working on results from thousands of TMS optimization simulations and I will not have the time to manually go thru and look at where the RAS coordinates correspond to in the brain using freeview for each result I get from the simulations. 

Thank so much.

**Comment by fangcao** [comment]
Hi @Tanush99, in the example, when you did affine transformation on -5.79115569, -5.97163587 and -8.00026189, you missed the part 'e-02', is it related to your issue? Moreover, we recommend you look at the affine transformation https://en.wikipedia.org/wiki/Affine_transformation, which will help you understand how to transform from one space to another.

For your second question, yes, you are right. The RAS coordinates vary from different MRI scans, so you will want to convert the MRI scans to the MNI space in order to compare them directly.

**Comment by Tanush99** [comment]
Hello @fangcao. Thanks for the information. I figured out the affine transformation details, but now am trying to do TMS optimization using the ADM method due to its fast speed. Currently, I am wanting to do TMS optimization using the H1 coil and the MagStim double cone coils which are additional coils provided by SimNIBS. Also, TMS optimization using the ADM method can only be done using "ccd" files. However, I am unable to find the H1 coil and MagStim double cone coils in the "ccd" format. I currently just have them in the nifti format. Is there any way you know to convert the coils from nifti format to "ccd" format or do you know where SimNIBS provides these coils in the "ccd" format. The only coils that I can find that are provided in "ccd" format by SimNIBS are MagStim 70mm Figure-of-eight and MagVenture MC B70.

**Comment by Tanush99** [comment]
Hello @fangcao. Thanks for the support so far. Currently, I am actually having some issues with TMS optimization. In particular, I setting a target in my Python Script which is [-7.82, 3.29, 12.69]. However, I am receiving errors stating "Did not find any elements within the defined target region". However, when I open up freesurfer and locate these coordinates on the T1 and T2 files used to construct the head model, I find it pointing to the subthalamic nucleus which is my optimization target:

T1 image:
![image](https://user-images.githubusercontent.com/63757371/129805554-f29b3f6c-b975-4f19-9b56-e373702d6057.png)


T2 image:
![image](https://user-images.githubusercontent.com/63757371/129805488-54875763-5eb8-4ba4-b5da-e5aa36a24a0e.png)

Since the subthalamic nucleus is within the target region, do you know why TMS optimization can't seem to detect it being there. This error comes for some headreco head models, but not for others where TMS optimization seems to detect the subthalamic nucleus within the target region.

Thanks,
Tanush

**Comment by fangcao** [comment]
Hi Tanush, 

What you want to do is probably to rerun `mri2mesh` or `headreco` in SimNIBS, then open the T1 and T2 images in the output folder to check the coordinates. The T1 and T2 you showed were not produced by SimNIBS, so it may not recognize the coordinates correctly. To make it consistent, please make sure you use the T1 and T2 images in the SimNIBS output folder. 

Regards,
Fang
