### ISSUE TITLE
TMS optimization output

### ISSUE THREAD

**Issue by SaraRomanella** [simnibs/simnibs#64]
Hi, SimNIBS forum! I am currently running some TMS optimization simulations and at the end in the folder the script creates different mesh files and one simnibs_simulations txt file. Although I can visually see the direction and target of the coil thanks to the mesh, I was wondering where and how I can extrapolate the final coordinates of the center of the coil (after the trials within the grid) and the coordinates of the hand of the coil direction, so I can use them in different analysis and real life setting. 
Thank you so much!!
Sara

**Comment by Kstoffer** [comment]
Hi Sara, when running the optimization the resulting position is output as the last part of the .txt file you mention. This is encoded as a 4x4 affine transformation matrix, that is the three first colums (excluding the forth row) represent unit vectors in x, y, and z direction respectively, using the typical figure-8 MagVenture coils the direction of the handle is negative/opposite of y. The last column represents the coil origin (centre position for allmost all coils).
Unfortunately, if you are using matlab interface, the position is not returned so you will have to read it from the .txt file, or just use the python interface directly. Here, it is returned, it is very easy to write the script in python too (see https://simnibs.github.io/simnibs/build/html/tutorial/tms_optimization.html) and you have the advantage that you don't need a matlab license + less memory use (no Matlab overhead).
Best,
Kristoffer
