### ISSUE TITLE
CAT12 failed, bad tissue contrast

### ISSUE THREAD

**Issue by Konohana0608** [simnibs/simnibs#65]
Dear SimNIBS Team

First of all, I would also like to thank you for creating this awesome pipeline. 
As I have just started to use it, I am still unfamiliar with the tool so please excuse me if I am just overlooking something here.

So after going through the tutorial I wanted to use the headreco pipeline on some different MRI data to get a segmented head model. But here I ran into some issues. When using the standard command: headreco all <ID> t1.nii.gz t2.nii.gz for three out of my 4 samples it seems like cat12 doesn't seem to work due to Bad tissue contrast in the MATLAB part, and the fourth sample failed later on due to Gmsh failing to mesh surfaces. When I try to run headreco with --no-cat, then it worked for 3 out of 4. As you clearly state that results should be much better using cat12, I would really like to be able to create these head segmentations using it. 
I saw in a different thread that someone had a similar issue and you recommended changing line 112 in the simnibs/msh/segment_SPM.m file. I did this but still seem to have the same problem. 
I attached screenshots of the error messages and also the log files. If you need any further information, please let me know.

Thank you already very much in advance for your help. I am looking forward to hearing from you.

![Error_message_cmd](https://user-images.githubusercontent.com/61539759/132818203-e15b9bc3-6f37-4970-a40a-639188de666d.jpg)
![Error_message_matlab](https://user-images.githubusercontent.com/61539759/132818207-6d640576-757d-41f2-88eb-118acc5f882c.jpg)
[spmcat_1.log](https://github.com/simnibs/simnibs/files/7142060/spmcat_1.log)
[spmcat_2.log](https://github.com/simnibs/simnibs/files/7142063/spmcat_2.log)
[spmcat_3.log](https://github.com/simnibs/simnibs/files/7142065/spmcat_3.log)
[spmcat_4_matlab_worked.log](https://github.com/simnibs/simnibs/files/7142068/spmcat_4_matlab_worked.log)

**Comment by oulap** [comment]
Hi,

Can you also include the full headreco_log.html for one subject that failed and one subject that ran successfully?

Thanks

**Comment by Konohana0608** [comment]
Yes sure, thank you for your help~~ 
I included three different logs: two where I used CAT12 and it failed at different stages, and the other one where I disabled it and was successful. As .html files don't seem to be supported I put them in a .zip file. 

Please let me know if you need anything else.

[headreco_logs.zip](https://github.com/simnibs/simnibs/files/7163233/headreco_logs.zip)

**Comment by oulap** [comment]
Thanks, I didn't see anything particularly weird in the log, so it's likely something to do with the scans. In the CAT12 QC figure the T1 looks fine although the top is cropped. Is it possible/allowed for you to share the problematic scan? These things are a bit tricky to debug remotely. In case sharing is allowed, please contact support@simnibs.org and we can setup the data transfer.

**Comment by Konohana0608** [comment]
Ok, I see. I will check with my supervisor if it is possible to share the scans and let you know by tomorrow. Thank you for the help so far. 
But as you mentioned that the T1 looked cropped, is it possible that for the CAT12 to work image quality needs to be better than without. Because the log of the one I sent you failed when leaving CAT12 enabled, this actually succeeded when I added the --no-cat option.

**Comment by Konohana0608** [comment]
Hy there
So I contacted your support email about a week ago to confirm that the problematic MRI scan can be transferred. As I have not heard back I was wondering how we can set up the data transfer? I thank you very much in advance for your continuous help~~
