### ISSUE TITLE
environment_linux.yml dependencies too old

### ISSUE THREAD

**Issue by 0nu** [simnibs/simnibs#66]
Hi there, 

I installed simnibs from git (https://simnibs.github.io/simnibs/build/html/installation/conda.html), using the [environment_linux.yml](https://github.com/simnibs/simnibs/releases/latest/download/environment_linux.yml) file. 
The dependency versions `environment_linux.yml` are very old, and at least scipy==1.2.1 does not work with the current (3.2.4) simnibs release, because the output format of scipy.ndimage.map_coordinates has changed:

https://github.com/simnibs/simnibs/blob/cbc114f109dd736fba73168d739c13873fd940c5/simnibs/msh/mesh_io.py#L3413

So far, numpy==1.21.2, h5py==3.4.0, and scipy==1.7.1 work for me.

When working on this, could you maybe get rid of the hard-coded conda environment name `simnibs_env` in the .yaml file / the pip installation of simnibs?

Bests,
Ole

**Comment by 0nu** [comment]
...`mkl` seems to be missing from the env file, for use of the pardiso solver.

**Comment by oulap** [comment]
Hi Ole,

Thanks for informing us. We're planning a minor update before the major one (where the dependencies are going to be changed a fair bit), so I can have a look at updating the outdated versions.

If you install simnibs using conda, you can just pass --name  <my_environment> which overwrites the default name.

-Oula
