### ISSUE TITLE
Headreco without mesh generation

### ISSUE THREAD

**Issue by StephenHogg** [simnibs/simnibs#69]
Hi,

I was wondering if I could check my understanding of how to use headreco is right. Specifically, if I just want the nifti file with all voxels classified as one of the tissue types, I would just run:

```
headreco preparevols
headreco preparecat
headreco cleanvols
```

Is this right? If so, where would I find the file I'm looking for in the output?

At the same time, I notice that during the preparecat stage of the process CPU utilisation tends to be very low while decoupling GM from WM. Is there anything I can do to make the process run faster?

Cheers,

Stephen

**Comment by oulap** [comment]
Hi Stephen,

Yes that's right. After those steps there should be a file called <sub_id>_masks_contr.nii.gz in the m2m-folder, which has the cleaned tissues. Alternatively the segment folder has the SPM and CAT12 runs, where you can find the tissue maps before the cleaning step. 

The decoupling step is done in a separate process. Are you sure you're looking at the correct process for the CPU usage?
