### ISSUE TITLE
Running Simnibs on WSL

### ISSUE THREAD

**Issue by ItayHadas** [simnibs/simnibs#77]
Hi,

I am trying to install SimNIBS on WSL.
I tried to run simnibs_installer for Linux and through conda, but in both cases I get blank gui window and errors when running simnibs_gui :
`QOpenGLWidget: Failed to make context current`
`qt.qpa.backingstore: composeAndFlush: makeCurrent() failed`

the graphic card is updated, VCXSRV is running, and only English chars in the path name (per you troubleshooting page). Please see screenshot:

Hope you can help!
Thanks!

![Gr2LJILA9I](https://user-images.githubusercontent.com/5610394/164612330-c6bf8349-fac0-4481-bb13-a6ba4a65b34b.png)

**Comment by 78furu** [comment]
Hey there, 

I also have the a similar issue, though, I have a little bit different setups:

- OS: Ubuntu 22.04.
- Video card driver: NVIDIA 510.73.75 (recommended by default)

I attached a screenshot of the terminal when I run `simnibs_gui`. A new window appears, but is also empty black. During the installation process I also got the error messages regarding the libraries `iris` and `swrast`. As of right now, after browsing through the web, I have no idea where the problem originates from. 

I would appreciate any help regarding this issue.

Thank you!

![simnibs_error](https://user-images.githubusercontent.com/26274581/169829107-e3685f72-70ad-4bd2-9a3c-34a4a2862af8.png)

**Comment by Kstoffer** [comment]
Yes, these are unfortunately know issue on any linux using Wayland graphics backend and appears to also affect any program using OpenGL via PyQT4 backend including pyvista. It should only affect the simnibs_gui, using the previous version of Ubuntu 20.04 (or another Linux distribution wihtout Wayland) should alleviate the issue.
We are currently looking into providing a more permanent fix for this.

**Comment by oulap** [comment]
The GUI should work on Wayland (and in 22.04) if you preload the system libstdc++.so.6, see example here:

https://simnibs.github.io/simnibs/build/html/changelog.html#changelog
