### ISSUE TITLE
Diffusion tensor information ignored

### ISSUE THREAD

**Issue by mlueckel** [simnibs/simnibs#79]
Hi,

whenever I run simulations, the diffusion tensor information in `d2c_subID/dti_results_T1space/DTI_conf_tensor.nii.gz` is being ignored, stating that "isotropic conductivities" are used. Any idea why that is?

Thanks,
Max

**Comment by axthi** [comment]
Hi, can you give more information on how you ran the simulations (via matlab, pyhton scripts or via the gui). If you ran it via scripts, please provide them to the support email, so that we can have a further look into it.
