### ISSUE TITLE
install: missing file operand 

### ISSUE THREAD

**Issue by ggrrll** [simnibs/simnibs#80]
hi, 

I am trying  to install the software on ubuntu, but I am getting that error

any idea?

thanks

**Comment by oulap** [comment]
Hi, 

Can you send the install log to support@simnibs.org, so we can have a look.

**Comment by ggrrll** [comment]
hi, 

somehow this error disappeared 

thanks anyway

**Comment by ggrrll** [comment]
btw, just figure out that that was simply due to the working directory 
(I was installing from inside simnibs_installer )
