### ISSUE TITLE
Single pulse or rTMS

### ISSUE THREAD

**Issue by flyxiaye** [simnibs/simnibs#83]
Hi!
Can the simNIBS work on single pulse stimulation or rTMS sitmulation? 
Thank you.

**Comment by Kstoffer** [comment]
Yes, the simNIBS calucated field changes are applicable in both cases.
It will just calculates the the static field which you modulate over time according to your desires. Explicitly note that simNIBS does not model any neural dynamics. 
Best,
Kristoffer
