### ISSUE TITLE
mri_convert: command not found 

### ISSUE THREAD

**Issue by ggrrll** [simnibs/simnibs#85]
Hi, 

I recently installed simNIBS and started testing it

when running `mri2mesh`  I get 

> /home/simNIBS/simnibs_env/lib/python3.7/site-packages/simnibs/bash_modules/mri2mesh: line 107: mri_convert: command not found exiting mri2mesh after error

any idea? 
(something wrong during the installation?)

thanks

**Comment by oulap** [comment]
Have you setup your FreeSurfer correctly? It should be in the path so mri2mesh can find it. Note mri2mesh only works with FS version <= 6.0, so version 7 and up will not work.

**Comment by ggrrll** [comment]
yeah, it was some configuration  issue 
-- sorry for the late reply
