### ISSUE TITLE
Two TMS coils in one simulation

### ISSUE THREAD

**Issue by SaraRomanella** [simnibs/simnibs#86]
Hi everyone, 
we are looking for investigating the electric field resulting from TMS with two coils in two different positions (ccPAS) with a simultaneous pulse. On the GUI I can see that I can set two positions and two coils but then the simulation runs independently for each. Is there any way to run a single simulation for both TMS pulse together and see the resulting NormE?
Thank you in advance,
Best, 
Sara

**Comment by Kstoffer** [comment]
Yes, you will have to run the two simulations independently and then manually combine the two E fields by adding the vectors in each position. Then if you require the magnitude of E (NormE) you have to calculate that again from the combined field. If you need more guidance on how to do that feel free to write back.
Best,
Kristoffer

**Comment by pedrohenrique1992** [comment]
Hello. I would like to know more information on how to sum the E fields for magnE and normE in order to then extract regional values.
