### ISSUE TITLE
Sinus erasure

### ISSUE THREAD

**Issue by StephenHogg** [simnibs/simnibs#88]
Hi,

My understanding is that the SimNIBS code removes the sinus from the segmented heads (hazily recalled from a previous conversation).

1. Is this the case?
2. Is it possible to disable this and ensure that the sinus is included as part of segmentation? For what it's worth, I don't necessarily care about the mesh files, only the segmented Nifti file.

Any thoughts or help greatly appreciated, thanks for all you do.

Regards,

Stephen

**Comment by oulap** [comment]
Hi Stephen,

The internal air cavities are removed from the mesh and as a result they're also not in <sub_id>_final_contr.nii.gz, but they should be labeled separately in <sub_id>_masks_contr.nii.gz. However the sinuses are part of the "internal_air" label so if you're interested in the sinuses specifically, you need to pull them apart from the rest of the air cavities yourself.

-Oula

**Comment by StephenHogg** [comment]
Thanks very much for your help, as usual
