### ISSUE TITLE
SimNIBS 4.0 beta 1 shows "svg did not converge" error for Charm

### ISSUE THREAD

**Issue by shanyechungu** [simnibs/simnibs#89]
Hi there,

when we tried to use Charm command with SimNIBS 4, it gave an error and suggested to use the --forceqform option. We then used the following charm command:

charm subj T1.nii.gz T2.nii.gz --forceqform

It kept giving an error of "svg did not converge"

Below are the details:

Version: SimNIBS 4.0 beta 1 for linxu
OS: Ubuntu 20.04.4 LTS
Command: charm subj T1.nii.gz T2.nii.gz --forceqform

Error message:
...
Read mesh collection: /data/m2m_M87144843/segmentation/atlas_level2.txt.gz
Transforming points
Transforming points
Read mesh collection: /data/m2m_M87144843/segmentation/atlas_level2.txt.gz
Read mesh collection: /data/m2m_M87144843/segmentation/atlas_level2.txt.gz
Constructing image-to-world transform from header information (/opt/SIMNIBS/simnibs_env/lib/python3.9/site-packages/simnibs/segmentation/atlases/charm_atlas_mni/template.nii)
Read image: /opt/SIMNIBS/simnibs_env/lib/python3.9/site-packages/simnibs/segmentation/atlases/charm_atlas_mni/template.nii
Read mesh collection: /data/m2m_M87144843/segmentation/atlas_level2.txt.gz
[ simnibs ]CRITICAL: Uncaught exception
numpy.linalg.LinAlgError: SVD did not converge

Any clue?

Thanks,

**Comment by oulap** [comment]
Hi,

Would it possible for you to provide these scans so I can have a look? I haven't encountered this error before, so it's a bit tricky to fix as I have no way of producing it at the moment.

Thanks

**Comment by oulap** [comment]
Are you still experiencing this issue with then new release? One possible workaround is to install the intel-numpy version from pip (https://pypi.org/project/intel-numpy/) as this likely relates to some of the blas libraries of your particular system.
