### ISSUE TITLE
incomplete outputs with charm 

### ISSUE THREAD

**Issue by ggrrll** [simnibs/simnibs#91]
Hi , 

thanks for the new beta-v. 

I am trying to visualise  the result of
`charm ernie ernie/org/ernie_T1.nii.gz`

with _3D slicer_  , but I don't see the segmentation layer...  am I missing something? 

thanks

ps: output folder structure

my _m2m_ernie_ has
_T1.nii  T1.nii.gz  charm_log.html  segmentation  settings.ini_

and _segmentation_ has
_atlas_level1.txt.gz  atlas_level2.txt.gz  coregistrationMatrices.mat  template_coregistered.mgz_

**Comment by oulap** [comment]
Can you send the charm_log.html to support@simnibs.org so we can have a look?

Thanks,
Oula

**Comment by ggrrll** [comment]
@oulap  did you have the time to have a look ? 
I wrote on 21/9

thanks in advance

**Comment by ggrrll** [comment]
fixed -- unrelated issue with virtual machines
