### ISSUE TITLE
How to obtain the electrode area and determine whether the electrodes overlap in Python?

### ISSUE THREAD

**Issue by Gott-L** [simnibs/simnibs#95]
Dear SIMNIBS developers,

 I used simnibs recently, it is really a great project, but I can't found the information about electrode area acquisitions, I need to check  whether the electrodes overlap, can you tell me how to do it in Python?

Thank you in advance for your reply.

Best regards

**Comment by oulap** [comment]
Hi,

You could check the mesh after simulation, extract the electrode elements and see if the element centers are too close to each other. You can use the mesh tools in SimNIBS to get the tetrahedra centers, or triangles, for the electrodes only and check the distances between the point sets of an electrode pair.

**Comment by Gott-L** [comment]
> Hi,
> 
> You could check the mesh after simulation, extract the electrode elements and see if the element centers are too close to each other. You can use the mesh tools in SimNIBS to get the tetrahedra centers, or triangles, for the electrodes only and check the distances between the point sets of an electrode pair.

Thank you very much. Could you give some example code or information about get the point sets of an electrode pair from simulation mesh result?Or can I get from the geo file?
Best regards!

**Comment by oulap** [comment]
Good to hear! Let us know if there are more problems.
