### ISSUE TITLE
spikes still present on charm segmentation

### ISSUE THREAD

**Issue by ggrrll** [simnibs/simnibs#99]
Hi, 

just performed a segmentation on T1 + T2 and I see there are still spikes , at the bottom of the cortex 👇
although , the spike removal step seems to be running fine -- here is the extract from logs:

```
INFO:  Step 3: Resolve remaining localized spikes 
INFO:      Testing 69002 nodes (matrix: (620249, 620249), 3144382 entries)
INFO:    Relabled 3280 tets
INFO: Done Removing Spikes: Total number of relabled tets: 85606
``` 

is it normal ? 

thanks 

<img width="842" alt="Screenshot 2022-11-01 at 15 05 08" src="https://user-images.githubusercontent.com/15370425/199260152-76325fcc-85ee-4e19-8852-76d378dc10be.png">

**Comment by oulap** [comment]
Hi,

We are aware of the GM surfaces being slightly spiky still. Cleaning out the surfaces better is high on the agenda and we hope to sort this out in a minor update soon, but for now the GM surfaces will not be as shiny as those output by headreco.

**Comment by ggrrll** [comment]
are there related parameters that can be tuned ?
